### ISSUE TITLE
Feature Request: Being able to define custom pages for "widget sets"

### ISSUE THREAD

**Issue by ConstantineK** [Microsoft/sqlopsstudio#175] opened 2017-11-21 16:14 UTC
Based on https://docs.microsoft.com/en-us/sql/sql-operations-studio/tutorial-build-custom-insight-sql-server it appears that currently if you want to add custom widgets to SOS have the option for Server and Database dashboards - I would like to request adding the option for an arbitrary amount of additional dashboards. 

The ability to define additional dashboards but without the additional visual clutter(search, db list, etc) would promote writing sets of widgets that might solve a particular problem (instead of giving you basic overview of your system health.)

This might allow the community to augment existing tools which produce useful data and shred them into more valuable insights which generally require significantly more experience before they are apparent (sp_whoisactive, sp_who2, dmv performance troubleshooting toolkit, etc.) 

I have seen many data ops people spending time with $VISUALIZATION_TOOL (and may even be good with it) to make a business case, to monitor a larger scale system, to track trends, etc; but when they finish the project it is difficult to share and get it widely adopted when (previously) the only thing you could guarantee the user had (without dropping additional money) was SQL Server and a SQL Client.

**Comment by anthonydresser** [comment] 2018-03-08 19:50
This sounds like it might be a dupe of #70 which I commented that we have a new tab system that would probably solve this problem.

**Comment by anthonydresser** [comment] 2018-03-08 19:51
I'm going to close this as a dupe, let me know if you don't believe it is.

**Closed by anthonydresser** 2018-03-08 19:51 UTC
Labels: dashboard, suggestion
