### ISSUE TITLE
Horizontal scrollbar is hard to use and see in dark mode

### ISSUE THREAD

**Issue by peterlukerow** [Microsoft/sqlopsstudio#2094] opened 2018-07-31 12:39 UTC
Issue Type: <b>Bug</b>

1. Open a SQL file with long text lines in and do a find for some text that appears part way through a long ling.
2. The text will be highlighted but a tiny hoizontal scrollbar thumb will appear not even a whole bar like the vertical one and only then when you happen to hover over it with the mouse. It's like half the number of pixels in height as the width of the vertical scroll bar.

Because of the difference between it and the vertical scrollbar I'm calling this a bug.
If it's by design then it's a poor UX.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>
Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (6.29GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|0.2.0
agent|Mic|0.31.4
profiler|Mic|0.1.2

</details>

**Comment by kburtram** [comment] 2018-07-31 17:59
@peterlukerow thanks for the issue.  This looks like a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/1964.  Please reactive if this is a different problem.

**Closed by kburtram** 2018-07-31 17:59 UTC

**Comment by peterlukerow** [comment] 2018-08-06 08:48
Okay thanks - glad to see it's on October roadmap. If you know anybody on the SSMS team can you give them a prod and tell them to hurry up and finish dark mode - you still need SSMS for various things.
