### ISSUE TITLE
datagrid sometimes selects multiple cells across results sets

### ISSUE THREAD

**Issue by dzsquared** [Microsoft/sqlopsstudio#2166] opened 2018-08-07 13:15 UTC
- SQL Operations Studio Version: 0.31.4

Steps to Reproduce:

Execute a query that produces multiple results sets with more columns than window width
Select a cell in the first result set
Scroll the first result set such that the selection is no longer visible
Select a cell in the second result set
press ctrl-C to copy
(clipboard now contains contents of the selected cell in the first result set)
![sqlops_copybug](https://user-images.githubusercontent.com/12227241/43777837-9626b3ba-9a19-11e8-84c0-84972b66b916.gif)

Not sure if this functionality is by design, the cell selection over multiple results sets seems to be intermittent so I suspect that this isn't the intended behavior.

**Comment by anthonydresser** [comment] 2018-08-07 19:00
This should be fixed by #2162, feel free to reopen if it isn't fixed in the next release.

**Comment by kburtram** [comment] 2018-08-07 19:01
@dzsquared this looks like the issue I merged a fix for this morning https://github.com/Microsoft/sqlopsstudio/pull/2162.  The fix will be available in the next `insiders` build later this week, or is available now by building off master.

I'll close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/2091.  Please reactive if the issue persists in the next published build.  Thanks!

**Closed by anthonydresser** 2018-08-07 19:00 UTC
