### ISSUE TITLE
Add "Result as Text"

### ISSUE THREAD

**Issue by shpsyte** [Microsoft/sqlopsstudio#1370] opened 2018-05-08 21:15 UTC
Hey, Please improve "result as text" like SSMS ? It's awesome feacture..

**Comment by kburtram** [comment] 2018-08-03 07:55
Closing as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/52.  Thanks for the suggestion.  Please leave any additional comments on the linked issue.

**Closed by kburtram** 2018-08-03 07:55 UTC
Labels: feature gap, query execution, suggestion
