### ISSUE TITLE
twice button "backup"

### ISSUE THREAD

**Issue by mingegneri** [Microsoft/sqlopsstudio#1357] opened 2018-05-05 12:06 UTC
Issue Type: <b>Bug</b>

select slq server instance
right click->manage
right click "details" on "last update" widget
it opens "backup view" with 2 buttons "backup"

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz (4 x 2794)|
|Memory (System)|7.89GB (1.53GB free)|
|Process Argv|D:\Utility\sqlops-windows\sqlops.exe|
|Screen Reader|no|
|VM|45%|

</details>Extensions: none
Reproduces without extensions

**Comment by kburtram** [comment] 2018-05-06 16:30
This looks like a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/1311.  Apparently it only repros if the window is closed with ESC character.  In any case, the fix should be in **May Public Preview** build tomorrow.

**Closed by kburtram** 2018-05-06 16:30 UTC
Labels: bug
