### ISSUE TITLE
Connection bar not appear when file extension is not *.sql

### ISSUE THREAD

**Issue by Bodaway** [Microsoft/sqlopsstudio#1180] opened 2018-04-18 12:12 UTC
- SQL Operations Studio Version: sqlops 0.27.3 (9474415ad68b5a70e8b851698c8c836664a9d5b5, 2018-03-27T05:25:59.481Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---
I have sql code in file with extension *.str, and the connection bar not appear.
I have configure *.str with sql.

![withbar](https://user-images.githubusercontent.com/5265578/38931041-6ad12bce-4301-11e8-99eb-422ad48e4768.PNG)
![withoutbar](https://user-images.githubusercontent.com/5265578/38931042-6aec7208-4301-11e8-8336-8d3a5ebec7f5.PNG)

Steps to Reproduce:

1. having sql code in file without *.sql extension into your workspace
2. try to execute the script

**Comment by Bodaway** [comment] 2018-04-18 12:16
same as #1039

**Comment by anthonydresser** [comment] 2018-04-18 18:01
I'm going to close as a dupe of #1039. When we fix that, the solution to this probably will be to add a file association to sql. Feel free to reopen if that won't fix this problem.

**Closed by anthonydresser** 2018-04-18 18:01 UTC
