### ISSUE TITLE
With enough select statements in a block of code, not all the results render correctly

### ISSUE THREAD

**Issue by tigerhawkvok** [Microsoft/sqlopsstudio#2097] opened 2018-07-31 17:31 UTC
Issue Type: <b>Bug</b>

Similarly, some of the results handling then acts buggy (such as chart viewing). 

![image](https://user-images.githubusercontent.com/165937/43476133-a5181aca-94ac-11e8-83f0-11b9ca4e0eca.png)

In fact, trying to view a chart on a blank-not-blank output seems to crash the output pane.

![image](https://user-images.githubusercontent.com/165937/43476217-d861cc82-94ac-11e8-9e0b-56afe13bfc3f.png)

and you can't leave this view

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (16.26GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment] 2018-08-07 23:11
I'm going to close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/156 so we can track this work in one place.  Please leave related feedback in https://github.com/Microsoft/sqlopsstudio/issues/156.

**Closed by kburtram** 2018-08-07 23:11 UTC
Labels: bug, feature gap, query editor
