### ISSUE TITLE
Keyboard arrow navigation in Servers view needs improvement

### ISSUE THREAD

**Issue by AchimHentschel** [Microsoft/sqlopsstudio#1120] opened 2018-04-11 08:24 UTC
- SQL Operations Studio Version: 
Version 0.27.3
Commit 9474415ad68b5a70e8b851698c8c836664a9d5b5
Date 2018-03-27T05:25:59.481Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
Connect to a database and open a databases' table node (or any non root node). When pressing left or right arrow keys nothing happens.
When doing this in other tree views (like in SSMS) these actions would 
- open a currently closed node
- step down to the first child node on an already opened node
- close a currently opened node
- step to the parent node if a node has already been closed

**Comment by kburtram** [comment] 2018-04-12 20:47
I think this is basically a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/727.  I'll add a note in that issue to review this one when resolve it.  Thanks for reporting.

**Closed by kburtram** 2018-04-12 20:47 UTC
Labels: object explorer, suggestion
