### ISSUE TITLE
Git Repo Folder is not persistent

### ISSUE THREAD

**Issue by CubsRep** [Microsoft/sqlopsstudio#79] opened 2017-11-16 15:38 UTC
- SQL Operations Studio Version: Latest

Steps to Reproduce:

- Open a repo folder 
- Close & Reopen the Ops studio
- Previously Git repo is not showing up unlike VS Code. Has to redo or readd the folder everytime I open the studio

**Comment by kburtram** [comment] 2017-11-16 18:46
@CubsRep sqlops should reopen the previously opened folder or workspace on start-up.  Is this the scenario you're referring to?  It looks like the Object Explorer viewlet is being automatically focused on startup, which appears to be a recent regression (previously active viewlet should still be active on restart), but the folder should be reopened in the Workspace Explorer viewlet.

**Comment by kburtram** [comment] 2017-12-01 17:26
@CubsRep I'm going to close this issue since I don't have a repro.  Please reactivate if the problem persists.

**Comment by benrr101** [comment] 2018-03-26 20:52
I am also unable to keep a folder open between startups.
My repro scenario:
* OSX 10.12.16
* SQLOps version: 889b60a71bb877087da90dd959a44bd4662db25d ("support grid container in nav section" from Feb 27th)
* Startup SQLOps
* Open workspace viewlet, no folders are open
* Click on the Open folder button select my usual folder
* SQLOps "restarts" with the folder open
* <kbd>cmd</kbd>+<kbd>q</kbd>
* Restart SQLOps, folder is not open again

**Comment by kburtram** [comment] 2018-03-27 00:58
@benrr101 I just tried the scenario you mentioned and still couldn't repro.

There's a similar scenario which I could repro behavior where the open folder is lost.  Though in this case the behavior matches VS Code.

1. Run SQL Ops Studio and open a folder.
2. Close the SQL Ops main window, but don't exit the process (on mac there is a difference from closing the window and exiting process using the `Quit SQL Operations Studio` command)
3. Open a new main window either using the `New Window` command or by double-clicking the application icon
4. New application window doesn't get the open folder settings from previous application window

Note: if the process is exited in step two and restarted then in my testing the open folder is retained.

Please let me know if you have additional details on your repro that would help diagnosis what's going on.

**Comment by kburtram** [comment] 2018-04-04 19:31
@benrr101 I'll close this again since I still don't have a repro.  Please reactive with updated repro details if you're still experiencing this.

**Closed by kburtram** 2018-04-04 19:31 UTC
Labels: bug, more info

**Comment by benrr101** [comment] 2018-04-05 23:51
After looking at this a bit more, I believe this is due to me using the `--extensionDevelopmentPath` flag.
1. Run SQLOps with `./scripts/sql.sh`
2. Close any folders in the workspace that are open -- this just resets your workspace for the next steps
3. Close SQLOps (I use <kbd>cmd</kbd>+<kbd>q</kbd> but as long as the process exits, it doesn't matter)
4. Open SQLOps with `./scripts/sql.sh --extensionDevelopmentPath=/path/to/extension`
5. Open a folder, which closes the existing window and opens a new one
6. Close SQLOps
7. Open SQLOps again with `./scripts/sql.sh --extensionDevelopmentPath=/path/to/extension`
8. The folder that was opened in step 5 will no longer be open

I've noticed this is the same behavior as in VSCode and it's an issue limited to extension development scenarios. Therefore, I'll close this. But at least now we have better details on how to repro.
