### ISSUE TITLE
Please add database diagramming

### ISSUE THREAD

**Issue by sam-wheat** [Microsoft/sqlopsstudio#1752] opened 2018-06-27 14:15 UTC
Issue Type: <b>Feature Request</b>

Please add database diagramming with the option to just show primary and foreign keys.

Thank you.

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 6.1.7601

**Comment by kevcunnane** [comment] 2018-06-27 18:05
This is a duplicate of #94. I'll close this as the majority of feedback was on this existing issue. Thanks for raising.

**Closed by kevcunnane** 2018-06-27 18:05 UTC
Labels: duplicate
