### ISSUE TITLE
Create as Script generates "Scripting Failed" error

### ISSUE THREAD

**Issue by djarekg** [Microsoft/sqlopsstudio#81] opened 2017-11-16 15:55 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. Right-click stored procedure and click "Create as Script"

![image](https://user-images.githubusercontent.com/671093/32900938-9ccbfe0a-cabc-11e7-8a6b-b930cd4317d1.png)

**Comment by llali** [comment] 2017-11-22 22:02
This is a duplicate of #177

**Closed by llali** 2017-11-22 22:02 UTC
Labels: bug, scripting
