### ISSUE TITLE
Script as... options should open query window connected to database

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#721] opened 2018-02-16 21:17 UTC
@MattIrv seems like we missed this scenario. Can you help fix / advise on how to fix?

Steps to Reproduce:
- Expand a DB in OE to show stored procedures
- Choose "Script as Execute" or another script option against an object
- It'll open in a new window, but disconnected

Expected:
- Since we know the DB context it should be connected to the existing DB like in SSMS. Also for Execute in particular, you definitely want to be connected.

**Comment by kburtram** [comment] 2018-02-16 21:33
Initially we wanted the editors to be disconnected for Script as Create since the CREATE statements will be squiggled with error underlines as duplicate entites.  For Script as Execute and Script as Alter the editor should be connected.

**Comment by kevcunnane** [comment] 2018-02-16 21:35
Script as Delete should also work in connected manner, correct? it's really just script as create that doesn't make sense. Agree on handling it in this manner, sounds like a good plan.

**Comment by Code-DJ** [comment] 2018-02-26 00:51
Additionally, including the USE database statement at the top would be nice. This way, when you manually connect, you don't end up updating the wrong database.

**Comment by kburtram** [comment] 2018-04-13 01:11
I'll close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/825#issuecomment-380979063

**Closed by kburtram** 2018-04-13 01:11 UTC
Labels: bug, object explorer
