### ISSUE TITLE
[uncaught exception in main]: Error: write EPIPE

### ISSUE THREAD

**Issue by pradm** [Microsoft/sqlopsstudio#1279] opened 2018-04-26 21:41 UTC
- SQL Operations Studio Version:
Version 0.28.4-insider
Commit 3d6fb7a8fa8e941306109f69bc094e307b9ff8c2
Date 2018-04-23T05:43:47.587Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
Hello Team,

On Windows when I launch SQL Ops Studio just before the application completely initializes if it go ahead and close the application it throws me the following message. It looks like its not able to gracefully shutdown the application and rather a termination. But the command line window is frozen but I don’t see sqlops process in TaskMgr at the same time I don’t see any application crash WER messages in the Event logs. TaskMgr analyze wait chain also doesn’t show up anything. If I hit enter again it brings the prompt back to me.

Is this a known issue which has been already reported? Am I doing anything wrong here – why WER is not able to detect the crash and generate a crash dump. Unfortunately I hadn’t enabled logging will validate if I can reproduce this consistently and either take some dumps or validate logging activity.

C:\Program Files\SQL Operations Studio>sqlops

C:\Program Files\SQL Operations Studio>
[main 2:30:38 AM] update#setState idle
[main 2:30:43 AM] [uncaught exception in main]: Error: write EPIPE
[main 2:30:43 AM] Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at Socket._writeGeneric (net.js:724:26)
    at Socket._write (net.js:743:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Socket.Writable.write (_stream_writable.js:241:11)
    at Socket.write (net.js:670:40)
    at Immediate.<anonymous> (C:\Program Files\SQL Operations Studio\resources\app\out\vs\code\electron-main\main.js:12270:35)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
 
![sqlopscrash](https://user-images.githubusercontent.com/27516588/39333348-253e88d6-49c8-11e8-8b56-0456b7a3e882.png)

Regards
Pradeep

**Comment by alanrenmsft** [comment] 2018-08-15 22:13
@pradm tried many times, couldn't reproduce the issue. Also, this seems to be a VSCode issue, they have a couple similar issues closed due to no repro. closing the issue for now.

@pradm Please reactivate the issue if you can reproduce it and share the dump with us. Thanks!

**Closed by alanrenmsft** 2018-08-15 22:13 UTC
Labels: bug, more info, shell, supportability

**Comment by pradm** [comment] 2018-08-16 12:52
I tried it on 0.31.4 and i do notice that it does not reproduce, Thanks for closing this issue. Will re-activate if this occurs again.

Version 0.31.4
Commit e026ab85a72c190cc4ccc834503aa9fe36dd6407
Date 2018-07-18T02:14:21.826Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
