### ISSUE TITLE
I cannot organize the server groups in the desired order I would like.

### ISSUE THREAD

**Issue by MAL-** [Microsoft/sqlopsstudio#531] opened 2018-01-22 18:06 UTC
- SQL Operations Studio Version: **0.25.4**

Steps to Reproduce:
Create Server Group folder and try to  sort them in any way. 

SQL-OPS does not allow you to sort it.

**Comment by kburtram** [comment] 2018-01-22 18:26
@MAL we'll log this suggestion into our backlog for upcoming Object Explorer fixes.  In the meantime, you should be able to reorder the server groups and connections in the User Settings file to sort the groups as you desire.  They should be displayed in the order they appear in the settings file.

**Comment by kburtram** [comment] 2018-04-13 01:42
I'll close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/335.  Thanks for the suggestion!

**Closed by kburtram** 2018-04-13 01:42 UTC
Labels: object explorer, suggestion
