### ISSUE TITLE
Scroll position in results pane lost when switching tabs

### ISSUE THREAD

**Issue by travis79** [Microsoft/sqlopsstudio#2587] opened 2018-09-14 15:21 UTC
Issue Type: <b>Bug</b>

Issue #114 seems to have returned in latest build

1. Run query in a tab
2. Scroll results pane to something other than initial position
2. Switch to a new tab
3. Switch back to original tab

Expected result:  Scroll position stays the same
Actual result:  Scroll position resets to initial position

SQL Operations Studio version: sqlops 0.33.5-insider (05040425df44c4ad60e6465e0322bf2c88b28e58, 2018-09-14T02:10:30.990Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (18.06GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.1.0
mssql-db-insights|mat|0.2.2
agent|Mic|0.32.7
import|Mic|0.1.0
profiler|Mic|0.1.5
server-report|Mic|0.1.3
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by abist** [comment] 2018-09-14 16:18
Closing this issue as it's a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/2514

**Closed by abist** 2018-09-14 16:18 UTC
