### ISSUE TITLE
The charts took a big step backwards

### ISSUE THREAD

**Issue by Korez73** [Microsoft/sqlopsstudio#2647] opened 2018-09-20 12:54 UTC
Issue Type: <b>Bug</b>

Write a query, run it.
Go to the chart view of the results
Expected: several chart types, line, pie, etc.
Actual: Only seeing chart and image as chart type options.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.10GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.32.7
profiler|Mic|0.1.5
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by Frank-Geisler** [comment] 2018-09-20 14:10
Hi Korez73!

I think this is the same issue that I reported here: #2646 .

Have a nice day

Frank

**Comment by kburtram** [comment] 2018-09-20 16:58
I'll close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/2646.  We're currently working a fix.  Sorry for the inconvenience.

**Closed by kburtram** 2018-09-20 16:58 UTC
Labels: bug, chart viewer
