### ISSUE TITLE
Integraded or Azure authentication 

### ISSUE THREAD

**Issue by german-ayala** [Microsoft/sqlopsstudio#2610] opened 2018-09-17 19:33 UTC
- SQL Operations Studio Version: 0.32.8 (0.32.8)

Steps to Reproduce:
Try to use azure ad credentials to connect to the database or sql server. We have database admins using their Azure accounts created through Azure admin and we so we need that option or else we'll have to create dupe SQL logins

**Comment by kburtram** [comment] 2018-09-17 20:11
@german-ayala I believe this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/13.  Please reactive if that issue doesn't capture your suggestion.  Thanks!

**Closed by kburtram** 2018-09-17 20:11 UTC
