### ISSUE TITLE
Add Script as Alter

### ISSUE THREAD

**Issue by HanzoX7** [Microsoft/sqlopsstudio#199] opened 2017-11-23 00:23 UTC
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:

1. Right-click on a stored procedure. 
2. Notice the lack of a Script as Alter option.

It would be very helpful to have this option... It would be even better if some variants could be added, like "Script as Alter to new tab" or "Script as Alter to clipboard".

**Comment by Ettemlevest** [comment] 2017-11-23 07:13
Duplicate of #24

**Comment by erickangMSFT** [comment] 2017-11-27 03:29
closing as a dupe of https://github.com/Microsoft/sqlopsstudio/issues/24

**Closed by erickangMSFT** 2017-11-27 03:29 UTC
