### ISSUE TITLE
Wrong output XML data in Chart Viewer AND Results

### ISSUE THREAD

**Issue by uniqalex** [Microsoft/sqlopsstudio#2180] opened 2018-08-08 12:00 UTC
- SQL Operations Studio Version: 0.31.4
- OS version: Windows 10 x64 Pro version 1803

Goal: I want to create insight for my dashboard. 
Steps to Reproduce:
1. Run query like this:
SELECT
    dm_exec_query_plan.query_plan
FROM sys.dm_exec_query_stats 
CROSS APPLY sys.dm_exec_sql_text(dm_exec_query_stats.plan_handle)
CROSS APPLY sys.dm_exec_query_plan(dm_exec_query_stats.plan_handle)
INNER JOIN sys.databases
ON dm_exec_sql_text.dbid = databases.database_id AND databases.database_Id = DB_ID()

This statement selects column with datatype = XML

2. In the results you can see this
![image](https://user-images.githubusercontent.com/22915408/43834155-cb4de75a-9b15-11e8-9111-ea80cd0bd581.png)

3. View as Chart
![image](https://user-images.githubusercontent.com/22915408/43834215-014a55c8-9b16-11e8-872a-d38053084278.png)

Wrong parsing xml column!

Expected behavior:
Results
![image](https://user-images.githubusercontent.com/22915408/43834376-8eda4484-9b16-11e8-8ca2-e4199f95d451.png)

Charts:
Table with links for opening query plan

**Comment by kburtram** [comment] 2018-08-08 16:39
@uniqalex this looks like a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/2086 which was a regression in the July Public Preview.  This issue should be fixed in the latest `insider` build available at https://github.com/Microsoft/sqlopsstudio/releases.  Please reactive if you continue to see the issue on the latest builds.

**Closed by kburtram** 2018-08-08 16:39 UTC

**Comment by uniqalex** [comment] 2018-08-09 06:37
Cool. 
Sorry that I didn't find it. 
![image](https://user-images.githubusercontent.com/22915408/43882261-beffe99c-9bb7-11e8-8651-55327bcdd025.png)

**Comment by uniqalex** [comment] 2018-09-05 15:56
0.32.8
The result set now looks good, but IT IS REALY SO SLOWLY scrolled ((
https://gyazo.com/5b9762711a4d422e290d4d54e7c49a32

But the problem with CHART Viewer is still exists
![image](https://user-images.githubusercontent.com/22915408/45105639-6034e200-b13d-11e8-933c-925c61763fde.png)
