### ISSUE TITLE
Results missing when executing a batch in a loop

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/sqlopsstudio#1493] opened 2018-05-25 21:30 UTC
When executing a batch in a relatively tight loop, the results seem to disappear after the first few resultsets.

**Sample Data:**

```
use VHTest;
create table VHTestTable(i int identity, c char(1));
insert into VHTestTable(c) select 'A' union select 'B' union select 'C';
```

**Sample Batch:**

```
use VHTest;
select top 10 * from VHTestTable v1 cross join VHTestTable v2;
waitfor delay '00:00:0.5';
go 10
```

**Output Messages:**

```
[2:26:55 PM]	Started executing query at Line 1
Beginning execution loop
(9 rows affected)
(9 rows affected)
(9 rows affected)
(9 rows affected)
(9 rows affected)
(9 rows affected)
(9 rows affected)
(9 rows affected)
(9 rows affected)
(9 rows affected)
Batch execution completed 10 times... 
Total execution time: 00:00:00.520
```

**Results:**

Look carefully - the 3rd resultset and all resultsets that follow show no values

![image](https://user-images.githubusercontent.com/8250560/40566938-fb0194ac-6027-11e8-8f50-893748ec91d0.png)

- SQL Operations Studio Version: 0.30.2-insider

**Comment by MattIrv** [comment] 2018-05-25 22:10
Probably the same bug as #799 and #1021 (planned to be fixed for the next release)

**Comment by kburtram** [comment] 2018-08-07 23:10
I'm going to close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/156 so we can track this work in one place.  Please leave related feedback in https://github.com/Microsoft/sqlopsstudio/issues/156.

**Closed by kburtram** 2018-08-07 23:10 UTC
Labels: bug, feature gap, query execution
