### ISSUE TITLE
Import CMS connections

### ISSUE THREAD

**Issue by bartedgerton** [Microsoft/sqlopsstudio#91] opened 2017-11-16 17:54 UTC
- SQL Operations Studio Version:  0.23.6

I have many database server connections in Central Management Server already.   Rather than having to go through the steps several times to setup all my servers, is there a way to import servers?

**Comment by kburtram** [comment] 2017-11-16 18:38
@bartedgerton I'll close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/17.  This is on our roadmap for prior to GA.

**Closed by kburtram** 2017-11-16 18:38 UTC
Labels: suggestion
