### ISSUE TITLE
Support Filtering in Object Explorer

### ISSUE THREAD

**Issue by Ryukote** [Microsoft/sqlopsstudio#858] opened 2018-03-07 07:56 UTC
I have noticed that you can't filter for example stored procedures like you can in SSMS with right click on Stored Procedures folder. This would be a nice feature.

**Comment by jakodev** [comment] 2018-03-15 16:02
It is one of my favorite features in ssms, I will really appreciate it

**Comment by tholap** [comment] 2018-03-20 23:57
right-click on database -> select "Manage" - there's a search field that's already way better than the filter in SSMS.

Though I would prefer to have that filter on the left side and always visible (not a couple of clicks away in a context menu). In a large database with hundreds of objects the tree becomes unusable and I always filter objects a lot.

**Comment by Ryukote** [comment] 2018-03-21 00:06
@tholap even tho this is actually a solution, it is not a good solution and here is why. You have opened a new sql document and you are typing something, you will right click on DB to select manage. What will happen is that sqlopsstudio will need to get out of that document view to have a new view where you can search. It should be realized like in SSMS so you can filter Object Explorer which is more ok.

**Comment by kburtram** [comment] 2018-04-13 01:18
Closing as duplicate of https://github.com/Microsoft/sqlopsstudio/issues/69.

**Closed by kburtram** 2018-04-13 01:18 UTC
Labels: suggestion
