### ISSUE TITLE
Changing tabs jumps to new location in file

### ISSUE THREAD

**Issue by kleinux** [Microsoft/sqlopsstudio#195] opened 2017-11-22 16:30 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. Open more than one file
2. Scroll down some in current tab
3. Change to new tab
4. Go back to previous tab

Usually the step 4 tab is back to the top, but sometime it is someplace "random" and maybe even with a new selection.

**Comment by spencrharstn** [comment] 2017-12-06 04:00
Note that it doesn't matter if you just scroll somewhere in a tab. The cursor resets if you're editing anywhere within the tab as well.

**Comment by erickangMSFT** [comment] 2017-12-06 17:11
@kleinux @spencrharstn agreed. this is a known issue. It will be improved. @saurabh500

**Comment by kleinux** [comment] 2017-12-06 17:21
Thanks @erickangMSFT. @spencrharstn I think this is a dupe of those tickets too.

**Comment by saurabh500** [comment] 2017-12-06 23:59
@spencrharstn 
>The cursor resets if you're editing anywhere within the tab as well.

I don't understand this statement. If you are in a single tab then the cursor resets?

**Comment by spencrharstn** [comment] 2017-12-07 00:33
@saurabh500 Sorry, let me clarify. Say you have two tabs open, each a query editing tab, Tab A and Tab B. Start editing anywhere in Tab B. Switch to Tab A. Then switch back to Tab B. The cursor is now at the beginning of the Tab B, not at the location you were editing, which is the expected behavior (as far as I know).

Does that make more sense?

**Comment by saurabh500** [comment] 2017-12-07 00:34
@spencrharstn Definitely makes sense now. 

I will close this issue as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/114 
You can subscribe to 114 for updates.

**Closed by saurabh500** 2017-12-07 00:34 UTC
Labels: bug, query editor
