### ISSUE TITLE
Copy With Headers adds headers before every row

### ISSUE THREAD

**Issue by nilamo** [Microsoft/sqlopsstudio#2375] opened 2018-08-30 15:14 UTC
Issue Type: <b>Bug</b>

In the results panel, if you right click and select "copy with headers", and then paste into another program (such as excel or VS Code), you'll see the headers have been added before each individual row, instead of just once before all rows.

SQL Operations Studio version: sqlops 0.32.7 (b3766d7421bac5d8596eb2ce4980da5546325282, 2018-08-30T02:59:53.029Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (8.07GB free)|
|Process Argv|E:\ProgramFiles\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by nilamo** [comment] 2018-08-30 15:17
This appears to be a duplicate of #2373 and #2372.  My mistake for not looking first.

**Comment by kburtram** [comment] 2018-08-30 15:48
@nilamo I'll close as a duplicate of the issues you mentioned.  We'll get a fix for this issue today.

**Closed by kburtram** 2018-08-30 15:48 UTC
