### ISSUE TITLE
CTRL+N behaviour

### ISSUE THREAD

**Issue by vectorkovacspeter** [Microsoft/sqlopsstudio#416] opened 2018-01-02 12:22 UTC
- SQL Operations Studio Version: 0.24.1

Steps to Reproduce:
1. connect to server
2. select a database
3. press ctrl+n

I expect the same result as SMSS, to open a new unnamed, empty query to the selected database, but the new query opens witouth connection, and I must specifí the connection by hand each time.
The function works, it I use right click on the database name, and choose 'New Query' option

**Comment by SebastianPfliegel** [comment] 2018-01-02 18:47
#6 pretty much sound like this issue.

**Comment by kburtram** [comment] 2018-01-02 18:56
Closing as a duplicate of #6.  We currently don't have a concept of "Global Active Connection" which we'll need to automatically establish a connected editor in the Ctrl-N scenario.  We'll add this within the next release or two based on the design and implementation complexity.

**Closed by kburtram** 2018-01-02 18:56 UTC
Labels: suggestion
