### ISSUE TITLE
sp_help [table] not showing constraints

### ISSUE THREAD

**Issue by Ryukote** [Microsoft/sqlopsstudio#1118] opened 2018-04-11 07:04 UTC
This issue was previously opened by me and closed since I tought the problem went away. #1047  @kevcunnane 

This time I got the same problem again and I will post screenshots here:

1) Here are screenshots from SSMS so there is proof that constraints exists:
    1.1.) showing table name https://imgur.com/hEdVHaO
    1.2.) showing constraints and references https://imgur.com/L7k7SNH

2) Here are screenshots from SQLOps so you can see that constraints and references are empty even tho they exist:
    2.1.) showing table name https://imgur.com/nOmYDWu
    2.2.) showing constraints and references https://imgur.com/9PVUhzI

I still don't Know what is the cause of this issue but it is strange that sometimes it works and sometimes it doesn't. I am always trayin to use sp_help [table] with shortcuts (I set it as ALT+F1).

**Comment by Ryukote** [comment] 2018-04-11 10:05
I have even tried to type sp_help [table] and same result. I can't see constraints and references.

**Comment by kevcunnane** [comment] 2018-05-01 16:36
#1305 looks like a duplicate of this. Given multiple users have reported this I'm guessing this raises issues in Slickgrid rendering or in the backend handling of multiple resultsets coming from 1 statement.

**Comment by llali** [comment] 2018-06-18 18:33
@anthonydresser I cannot repro this issue. Is it possible you already fixed it? I know you fixed some rendering issues in slickgrid.

**Comment by anthonydresser** [comment] 2018-06-18 18:38
It's possible I suppose. I'm not sure how to repro this

**Comment by llali** [comment] 2018-06-18 18:41
@kevcunnane do you have a repro for this bug? when I run EXEC sp_help 'Sales.CustomerTransactions' on AdventureWorks, I always get the constraints table

**Comment by kevcunnane** [comment] 2018-06-18 18:58
This is basically a "when showing 3 or more grid results, often the grids after the 1st show as empty".

**Comment by anthonydresser** [comment] 2018-06-18 19:02
If thats really what this bug is about, we can probably close this as a dupe. Fixing up the query results is part of a larger term fix I am doing as committer work.

**Comment by llali** [comment] 2018-06-18 19:18
closing as duplicate

**Closed by llali** 2018-06-18 19:18 UTC
Labels: bug, query execution
