### ISSUE TITLE
Change "Double-click a word to select entire word" behavior to include # and @ symbols

### ISSUE THREAD

**Issue by sebcruz** [Microsoft/sqlopsstudio#1266] opened 2018-04-25 20:51 UTC
Currently when you double-click any contiguous string of characters, that entire string will be selected for easy copying.  However the behavior currently ignores special characters commonly used in TSQL including @ and # signs.  This reduces the utility of the double-click to select feature.

Example:
select
    MyField = @MyParameter
    ,*
from #MyTempTable

Action:
Double-click with the cursor anywhere within "#MyTempTable" or
Double-click with the cursor anywhere within "@MyParameter"

Current Behavior:
The exact text "MyTempTable" will be selected ignoring the # sign
The exact text "MyParameter" will be selected ignoring the @ sign

Proposed Behavior
The entire text "#MyTempTable" will be selected including the # sign
The entire text "@MyParameter" will be selected including the @ sign

**Comment by kburtram** [comment] 2018-04-25 20:58
@sebcruz this looks like a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/143.  Please reactive if this isn't the same issue.  Thanks for reporting.  I agree we need to fix this.

**Closed by kburtram** 2018-04-25 20:58 UTC
Labels: intellisense, suggestion
