### ISSUE TITLE
Restore from file unselectable

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/sqlopsstudio#1579] opened 2018-06-07 16:51 UTC
- SQL Operations Studio Version:
0bf642d

Steps to Reproduce:
Restore from file is unselectable in the dropdown

**Comment by kburtram** [comment] 2018-06-12 16:02
I just opened a duplicate of this issue at https://github.com/Microsoft/sqlopsstudio/issues/1614.  I close this one since I provided screenshots 😄

**Closed by kburtram** 2018-06-12 16:02 UTC
Labels: bug, regression, restore
