### ISSUE TITLE
Result set hidden when not initially visible

### ISSUE THREAD

**Issue by andreujuanc** [Microsoft/sqlopsstudio#938] opened 2018-03-20 00:21 UTC
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

I get this:
![image](https://user-images.githubusercontent.com/360052/37628965-53ab94fc-2bdc-11e8-9eb4-8e1def5ba5c5.png)

Steps to Reproduce: (time to time i get this on different scenarios, but this one is one of the most recurrent)

1. Two SP, One calls the second 10 times, via while.
2. Second SP gets parameter and just does SELECT @Action Action
3. Resultsset hidden , wont show results after moving scrolls

Let me know if I can provide more data. 

Cheers

Update: 
 Same query in SSMS:
![image](https://user-images.githubusercontent.com/360052/37629110-33701b62-2bdd-11e8-988f-ad05867b66ef.png)

**Comment by kburtram** [comment] 2018-08-07 23:09
I'm going to close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/156 so we can track this work in one place.  Please leave related feedback in https://github.com/Microsoft/sqlopsstudio/issues/156.

**Closed by kburtram** 2018-08-07 23:09 UTC
Labels: bug, feature gap, query editor
