### ISSUE TITLE
No script was returned when scripting as Create on object StoredProcedure

### ISSUE THREAD

**Issue by rednaxel22** [Microsoft/sqlopsstudio#128] opened 2017-11-17 16:49 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Connect to a VM 
2. Open a database existing in the VM
3. Check the Programmability -> StoresProcedures
4. Right click an stored procedure and click on "Script as Create"

**Comment by erickangMSFT** [comment] 2017-11-21 13:52
@rednaxel22 This is under investigation. Can you confirm that the SP is not encrypted?

**Comment by rednaxel22** [comment] 2017-11-21 15:35
Is not encrypted.

**Comment by llali** [comment] 2017-11-22 22:00
This is a duplicate of #115

**Closed by llali** 2017-11-22 22:00 UTC
Labels: bug, scripting
