### ISSUE TITLE
Feature Request: SQL Agent option

### ISSUE THREAD

**Issue by pmpjr6465** [Microsoft/sqlopsstudio#68] opened 2017-11-16 13:48 UTC
Some sort of SSMS ish SQL Agent representation would be helpful.

**Comment by B4PJS** [comment] 2017-11-16 13:51
Duplicate of https://github.com/Microsoft/sqlopsstudio/issues/27 #27

**Comment by kburtram** [comment] 2017-11-16 18:30
@pmpjr6465 I'll close this as a duplicate of #27.  This is on our roadmap prior to GA, though we haven't started this work yet.

**Closed by kburtram** 2017-11-16 18:30 UTC
Labels: suggestion
