### ISSUE TITLE
Connection is not recognized when open script

### ISSUE THREAD

**Issue by gabcastro** [Microsoft/sqlopsstudio#405] opened 2017-12-28 13:37 UTC
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 6.3.9600
---

Steps to Reproduce:

1. Select some object in window manage of database
2. Select "Script as ..."
3. When open the window with code is possible to see that the connection wasn't recognized

To solve I always need to click on "Connect" and select the specific connection.
I saw too that the only place that is recognized auto is when I click on "New Query".

Regards,

**Comment by kburtram** [comment] 2018-01-02 20:34
@gabcastro this was initially "by design" for Script As Create since otherwise the `CREATE` statement would be flagged as a syntax error (something like 'Can't create an object that already exists`).  This design doesn't make sense for other scripting options such as Script As Alter or Script As Delete.  We'll take a look and see how to improve the experience.

**Comment by kburtram** [comment] 2018-04-13 01:34
Closing as duplicate of https://github.com/Microsoft/sqlopsstudio/issues/82.  Thanks for the suggestion.

**Closed by kburtram** 2018-04-13 01:34 UTC
Labels: scripting, suggestion
