### ISSUE TITLE
Scrollbar not fixed

### ISSUE THREAD

**Issue by rickeew** [Microsoft/sqlopsstudio#2132] opened 2018-08-02 21:43 UTC
Issue Type: <b>Bug</b>

Changing between queries in Operation Studio, shows issue with scrollbar.
This don't stay fixed in the last line visited, always come back to the beginning of document.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|5.88GB (1.23GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|0.2.0
profiler|Mic|0.1.2
whoisactive|Mic|0.1.1

</details>

**Comment by MattIrv** [comment] 2018-08-02 23:18
This bug will be fixed in the next release. A partial fix is already included in [the latest insiders build](https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.2.1), so check that out if you're interested. See #1845 for more details - I'll close this issue since it's a duplicate of that

**Closed by MattIrv** 2018-08-02 23:18 UTC
