### ISSUE TITLE
Feature Request: Right click on table name to Script as Insert

### ISSUE THREAD

**Issue by bcmartinez** [Microsoft/sqlopsstudio#499] opened 2018-01-16 23:33 UTC
- SQL Operations Studio Version: 0.24.1

Steps to Reproduce: When right clicking on a table name in the Servers panel, there are options to "Script as Create" and "Script as Delete". It would be useful to have a "Script as Insert" option that would write out an insert statement:

```
INSERT INTO DatabaseName.dbo.TableName
	(Field1, Field2, Field3)
VALUES 
	('', '', '')
```

Ideally, it would intelligently include the single quotes only if the field is a text field, and include an "N" if the field is nvarchar, like this:

```
INSERT INTO DatabaseName.dbo.TableName
	(TextField, IntField, NvarcharField)
VALUES 
	('', , N'')
```

**Comment by kburtram** [comment] 2018-07-19 16:15
I'm closing this as duplicate of https://github.com/Microsoft/sqlopsstudio/issues/459.  Please add comments on that issue if desired.

**Closed by kburtram** 2018-07-19 16:15 UTC
Labels: new feature ask, object explorer, scripting
