### ISSUE TITLE
Possibility to group table in schema

### ISSUE THREAD

**Issue by JeyDi** [Microsoft/sqlopsstudio#1793] opened 2018-06-29 08:09 UTC
- SQL Operations Studio Version: 0.30.6

Steps to Reproduce:
It's good to have the possibility to regroup the table in schema.
When you press the arrow near the schema you can find all the table associated.
This option can be enabled in the settings.
Like this SSMS extension: https://github.com/nicholas-ross/SSMS-Schema-Folders

**Comment by kburtram** [comment] 2018-06-29 20:18
@JeyDi this looks like a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/7.  Please consider upvoting that issue, or reactive if this is a different suggestion.  Thanks!

**Closed by kburtram** 2018-06-29 20:18 UTC
