### ISSUE TITLE
Save As Excel Only Saves First Row of Data

### ISSUE THREAD

**Issue by ryharris89** [Microsoft/sqlopsstudio#2371] opened 2018-08-30 14:13 UTC
Issue Type: <b>Bug</b>

When trying to save the results of a query as an Excel document, before the July update I would be able to perform the following steps with success:

Select All
Save As Excel

The result would push all data from the results into an Excel document. 

After the July update, this same process only saves the first row of data into the Excel document.

SQL Operations Studio version: sqlops 0.32.7 (b3766d7421bac5d8596eb2ce4980da5546325282, 2018-08-30T02:59:53.029Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (3.53GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2

</details>

**Comment by kburtram** [comment] 2018-08-30 14:32
@ryharris89 could you please try the repro without first Selecting All (so just having a single cell selected, for example)?  I looks like there may be something wrong with how we're determining the selection range.

**Comment by ryharris89** [comment] 2018-08-30 15:27
@kburtram When selecting just a single cell then clicking Save to Excel, everything works as I would expect the Save All, Save To Excel process. When opening the Excel document, both the headers and all rows of data are visible in the same format as present in the table.

**Comment by kburtram** [comment] 2018-08-30 15:55
@ryharris89 thanks for confirming.  This release has significant query results grid refactoring to better support Accessibility scenarios and it appears we didn't get the Select All behavior correct.  We'll work on a fix today and publish an updated August release once we've triaged through all the regressions in the the `0.32.7` build.  Sorry for the inconvenience.

**Comment by kburtram** [comment] 2018-08-30 17:02
@abist could you please look at this issue?  I think it's related to the Copy w/ Headers bug you already looked at.  Thanks!

**Comment by abist** [comment] 2018-08-30 21:45
This should be fixed in https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.8. Please re-open the issue if the problem persists in the latest build.

**Closed by abist** 2018-08-30 21:45 UTC
Labels: bug, query editor, regression
