### ISSUE TITLE
Standby database 

### ISSUE THREAD

**Issue by pazitzik** [Microsoft/sqlopsstudio#218] opened 2017-11-26 19:38 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1.connect to a remote server ,in my case a dwh server .
2.some of database in dwh instance are in standby mode (from logshipping)
![image](https://user-images.githubusercontent.com/20770094/33243606-104239b6-d2f2-11e7-80f9-5cbe4e816087.png)

as you can see the databases are inaccessible .

**Comment by kburtram** [comment] 2018-04-13 00:53
Closing as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/272

**Closed by kburtram** 2018-04-13 00:53 UTC
Labels: bug, object explorer
