### ISSUE TITLE
HotExit feature doesn't work

### ISSUE THREAD

**Issue by Leoat12** [Microsoft/sqlopsstudio#435] opened 2018-01-04 00:29 UTC
- SQL Operations Studio Version: 0.24.1

Steps to Reproduce:

1) Check on File > Preferences > Settings if files.hotExit is with value "onExit"
2) Try to close the application with files opened.

The expected behavior, like in VSCODE is to skip the save prompt and resume from where you left off when you open it again, but the prompt appears and the files are not save for further session. 
Really like this feature from VSCODE, so I would like to point it out if it is not implemented yet. 

Thanks in advance for the support and for the amazing application, I'm loving it!

**Comment by kburtram** [comment] 2018-01-04 01:01
@Leoat12 we ran into several issues enabling HotExit due to the way we create a custom "SQL Editor".  This merged PR should resolve the last remaining known issue and enable HotExit by default [#385 Fix issue where loading unsave sql file open as untitiledEditorInput](https://github.com/Microsoft/sqlopsstudio/pull/385).  

Though we still need to put some additional testing mileage on that change before releasing.  If you build from master you should get this change.  I'll post a test candidate build with the latest fixes from master later this week once a few regressions in master are resolved.

**Comment by Leoat12** [comment] 2018-01-04 10:24
Thank you for the answer! I think I will try it out and test it a bit building from source and keep tracking the releases.

**Comment by kburtram** [comment] 2018-01-04 21:02
@Leoat12 fyi, this insiders build has hotexit enabled https://github.com/Microsoft/sqlopsstudio/releases/tag/0.25.0.  Assuming we don't find further blocking issues this will be in the Jan. release later this month.

**Comment by Leoat12** [comment] 2018-01-04 23:45
I installed it and I will be testing from now on, if I see anything wrong, I will post an issue here. By the first utilization I can perceive a performance improvement besides the Hot Exit working. Thank you for the great job!

**Comment by kburtram** [comment] 2018-01-17 23:50
HotExit is available in the January release, but needs to be explicitly enabled in the user settings.  We'll enable by default in a future release once we're confident in the quality of the implementation (likely in Feb release).

**Closed by kburtram** 2018-01-17 23:50 UTC
Labels: bug, shell
