### ISSUE TITLE
Crashes when trying to connect to Azure DB

### ISSUE THREAD

**Issue by ovidiaconescu** [Microsoft/sqlopsstudio#107] opened 2017-11-17 06:56 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. Stack Trace:
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No such host is known.) ---> System.ComponentModel.Win32Exception (0x80004005): No such host is known
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass22_0.<TryGetConnection>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in C:\J\jobs\sqltoolsservice_master_win\workspace\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableSqlConnection.cs:line 298
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.<TryOpenConnection>d__46.MoveNext() in C:\J\jobs\sqltoolsservice_master_win\workspace\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 542
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:11001,State:0,Class:20

**Comment by kevcunnane** [comment] 2017-11-20 21:16
@ovidiaconescu this looks like a connection error - we're working to hide the stack trace from the main dialog so it's clearer that this is usually an issue with the connection. 

In this case, the error is showing that it didn't find the server. Specifically `No such host is known` indicates a DNS lookup failure. I would recommend making sure you add `.database.windows.net` to your server name to connect. 
- See https://docs.microsoft.com/en-us/sql/sql-operations-studio/quickstart-sql-database for information on how to set up an Azure SQL Database connection

I'm going to close this out as it's expected behavior of the application and the solution is to get the correct server name for connecting.

**Closed by kevcunnane** 2017-11-20 21:16 UTC
Labels: bug

**Comment by ovidiaconescu** [comment] 2017-11-20 23:20
@kevcunnane thanks! Not sure what the issue was, but I was using it with `.database.windows.net` in SQL Management Studio and I copied the details from there.
Anyway, it now works. Thanks!

**Comment by sandeepnegi1996** [comment] 2019-02-25 09:27
I am using the server name with the .database.windows.net but it still not working 
don't know why it is not working. I am inside a corporate don't know whether it is because the proxy or not
