### ISSUE TITLE
Databases did not show in object explorer

### ISSUE THREAD

**Issue by ibrowne** [Microsoft/sqlopsstudio#121] opened 2017-11-17 13:56 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:46:54.710Z)
- OS Version: Darwin x64 16.7.0
---

Steps to Reproduce:

1. Connected to server (started new connection)
2. Expanded the server in the object explorer, saw the `Databases`, `Security`, and `Server Objects` folders.
3. Clicked on `Databases` to expand it, and a spinning wheel of death spun next the folder icon for a while, then I see this with no databases listed: https://www.screencast.com/t/p08y0GpmqEn

**Comment by kevcunnane** [comment] 2017-11-20 21:26
@llali are you taking this one? Or is it a duplicate of a similar issue you fixed?

**Comment by llali** [comment] 2017-11-20 21:27
it's a duplicate of #12

**Comment by kevcunnane** [comment] 2017-11-20 21:31
Thanks @llali. Closing as a duplicate. @ibrowne this is fixed internally and will be included in the next release. Thanks for reporting!

**Closed by kevcunnane** 2017-11-20 21:31 UTC
Labels: bug, duplicate, object explorer
