### ISSUE TITLE
Feature. Create table interface

### ISSUE THREAD

**Issue by ECWeb** [Microsoft/sqlopsstudio#2136] opened 2018-08-03 08:31 UTC
Is it possible to have something like create table feature like SSMS in the future?

**Comment by kburtram** [comment] 2018-08-03 20:46
@ECWeb thanks for the suggestion.  I believe this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/1712.  Please reactive if this is a separate issue.

**Closed by kburtram** 2018-08-03 20:46 UTC
