### ISSUE TITLE
Friendly names for connections

### ISSUE THREAD

**Issue by CobusKruger** [Microsoft/sqlopsstudio#240] opened 2017-11-29 08:28 UTC
Presently, I can add several connections to functional groups with nice, people-friendly names. But the connections themselves show the full **ServerName\InstanceName, DatabaseName** text, which (in our organisation's case at least) can be quite long and onerous. 

I'd much prefer to be able to assign friendly names to the connection and have that display instead. Or, you could show both the friendly name and the robot name.

Attached, I have a mock-up of three display options. From top to bottom: 

1. The current system
2. Friendly name only
3. Hybrid (my favourite)

![sqlopsconnectionpanel](https://user-images.githubusercontent.com/10893522/33365172-f8a9b770-d4ef-11e7-9d90-dddfe1268757.png)

- SQL Operations Studio Version:
0.23.6
Steps to Reproduce:
1. Look at the connection panel. 
2. See it shows names in the format **ServerName\InstanceName, DatabaseName**
3. Create this feature request

**Comment by primordius** [comment] 2017-11-29 19:08
I would like to see this feature as well, came here to suggest this exact feature.
I often require SSH tunneling to access remote production servers.
All I can see in the connection name is "localhost,<port>"

**Comment by erickangMSFT** [comment] 2017-12-08 17:11
duplicate of https://github.com/Microsoft/sqlopsstudio/issues/66 This issue is selected.

**Closed by erickangMSFT** 2017-12-08 17:11 UTC
Labels: connection, suggestion
