### ISSUE TITLE
Edit results in grid

### ISSUE THREAD

**Issue by pfaisant** [Microsoft/sqlopsstudio#65] opened 2017-11-16 13:16 UTC
- SQL Operations Studio Version:

Steps to Reproduce:

**Comment by kevcunnane** [comment] 2017-11-16 19:05
We currently support edit data as an option from Object Explorer and the Search widget in the dashboard. We don't have plans to add inline editability to results panes at this time.

**Comment by kburtram** [comment] 2018-04-13 01:16
Closing as duplicate of https://github.com/Microsoft/sqlopsstudio/issues/78 which is targeting April Public Preview release.

**Closed by kburtram** 2018-04-13 01:16 UTC
Labels: edit data, suggestion

**Comment by Zyxious** [comment] 2018-12-12 09:42
This is one of the main reasons I don't switch to SQL Operations Studio.
