### ISSUE TITLE
Edit Data Tab don't keep scroll down status

### ISSUE THREAD

**Issue by kkbruce** [Microsoft/sqlopsstudio#299] opened 2017-12-07 06:31 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. Table --> Edit Data --> Scroll down some row
2. Change other Tab and back Edit Data Tab
3. Scroll always back to **top**

Let Edit Data Tab keep scroll down status.

**Comment by kburtram** [comment] 2018-04-11 18:18
I think this is basically the same issue as https://github.com/Microsoft/sqlopsstudio/issues/114, though since that is tracking Query Editor and this is tracking Data Editor let's keep it open to make sure both editors are correctly fixed.

**Comment by kburtram** [comment] 2018-07-16 17:24
Closing as duplicate of #114 to reduce number of related issues.  I'll make a note in#114 to also look at the Edit Data scenario.

**Closed by kburtram** 2018-07-16 17:24 UTC
Labels: bug, edit data
