### ISSUE TITLE
Feature request: Please make the results grid auto-fit column width to data, and/or remember manual changes if the same query is re-run

### ISSUE THREAD

**Issue by Ettery** [Microsoft/sqlopsstudio#1204] opened 2018-04-23 13:14 UTC
- SQL Operations Studio Version: 0.27.3

It's frustrating having to widen the text and datetime columns every time a query is run to see the results.

**Comment by thinkOfaNumber** [comment] 2018-05-15 02:04
Is this a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/172?

**Comment by Ettery** [comment] 2018-05-16 16:52
Yes, I'd say so.

**Comment by kburtram** [comment] 2018-05-16 17:50
@Ettery I'll close this as a duplicate of #172.  We are planning this work in a subsequent release.

**Closed by kburtram** 2018-05-16 17:50 UTC
Labels: query editor, suggestion

**Comment by GrzegorzLyp** [comment] 2018-05-18 14:57
In 0.30.1 does not look good.

![image](https://user-images.githubusercontent.com/29247982/40241948-802b08dc-5abc-11e8-9fd6-f6299dc00956.png)

**Comment by AlexCoderCorp** [comment] 2018-06-07 09:05
In 0.30.3 does not work
![image](https://user-images.githubusercontent.com/25246926/41089679-789c5eda-6a53-11e8-941c-52bc067237b7.png)

**Comment by kr3wangel** [comment] 2018-06-11 16:21
Yep, this feature is definitely not working
![autofix](https://user-images.githubusercontent.com/18352469/41243976-f1cb7e70-6d60-11e8-8f28-8bca9674ca5f.JPG)

**Comment by mgnoonan** [comment] 2018-06-25 20:52
Just curious why this issue is listed in the [June Release Notes](https://docs.microsoft.com/en-us/sql/sql-operations-studio/release-notes?view=sql-server-2017) when:

- There are no code commits for the issue.
- It's not the primary tracking issue, which seems to be #172 
- That issue has a milestone of August

Release tracking get messed up somewhere?

**Comment by nitzien** [comment] 2019-02-21 09:03
This is still not fixed. At least having a resultsGrid.cellwidth will help.
