### ISSUE TITLE
Feature Request: Results Grid Navigation 

### ISSUE THREAD

**Issue by DianGermishuizen** [Microsoft/sqlopsstudio#1178] opened 2018-04-18 09:46 UTC
- SQL Operations Studio Version: 0.27.3

Request: When selecting a cell in the results grid, allow the user to select and drag off screen, thereby moving the results grid and selecting cells just like SSMS.

**Comment by anthonydresser** [comment] 2018-04-18 18:02
dupe of #1007

**Closed by anthonydresser** 2018-04-18 18:02 UTC
