### ISSUE TITLE
occasional error loading the tab content

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/sqlopsstudio#1686] opened 2018-06-20 06:17 UTC
I've been seen this error occasionally, and I had to reload the app.

[Extension Host] rejected promise not handled within 1 second (at Timeout._onTimeout (e:\git\sqlopsstudio\out\vs\workbench\node\extensionHostProcess.js:60:37))
zone-node.js:2251
  ERR No component factory found for FormContainer. Did you add it to @NgModule.entryComponents?: Error: No component factory found for FormContainer. Did you add it to @NgModule.entryComponents?
zone-node.js:2251
    at noComponentFactoryError (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:3330:34)
    at _NullComponentFactoryResolver.resolveComponentFactory (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:3348:15)
    at CodegenComponentFactoryResolver.resolveComponentFactory (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:3390:87)
    at ModelComponentWrapper.loadComponent (file:///E:/git/sqlopsstudio/out/sql/parts/modelComponents/modelComponentWrapper.component.js:97:67)
    at ModelComponentWrapper.ngAfterViewInit (file:///E:/git/sqlopsstudio/out/sql/parts/modelComponents/modelComponentWrapper.component.js:60:22)
    at callProviderLifecycles (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:11168:18)
    at callElementProvidersLifecycles (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:11143:13)
    at callLifecycleHooksChildrenFirst (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:11127:17)
    at checkAndUpdateView (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12159:5)
    at callViewAction (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execEmbeddedViewsAction (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12472:17)
    at checkAndUpdateView (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12152:5)
    at callWithDebugContext (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (E:\git\sqlopsstudio\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at ModelViewContent.ViewBase.initializeModel (file:///E:/git/sqlopsstudio/out/sql/parts/modelComponents/viewBase.js:39:28)
    at file:///E:/git/sqlopsstudio/out/sql/workbench/api/node/mainThreadModelView.js:51:27
    at MainThreadModelView.execModelViewAction (file:///E:/git/sqlopsstudio/out/sql/workbench/api/node/mainThreadModelView.js:89:26)
    at MainThreadModelView.$initializeModel (file:///E:/git/sqlopsstudio/out/sql/workbench/api/node/mainThreadModelView.js:50:25)
    at RPCProtocol._doInvokeHandler (file:///E:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:215:27)
    at RPCProtocol._invokeHandler (file:///E:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:200:54)
    at RPCProtocol._receiveRequest (file:///E:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:155:50)
    at RPCProtocol._receiveOneMessage (file:///E:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:138:26)
    at file:///E:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:75:92
    at file:///E:/git/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:248:21
    at Emitter.fire (file:///E:/git/sqlopsstudio/out/vs/base/common/event.js:103:38)
    at Socket.<anonymous> (file:///E:/git/sqlopsstudio/out/vs/base/parts/ipc/node/ipc.net.js:90:46)
    at ZoneDelegate.invokeTask (E:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (E:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (E:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:496:34)
    at Socket.ZoneTask.invoke (E:\git\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)

**Comment by abist** [comment] 2018-06-20 16:06
I get this error only when I "refresh" the app while running yarn run watch the first time, but it works if you close and open the app again. I think the extension doesn't compile at once like the main app does and that's why we see this error.

**Comment by llali** [comment] 2018-06-20 16:10
seems to be duplicate of this: https://github.com/Microsoft/sqlopsstudio/issues/1631

@anthonydresser  I also see this error sometimes. I feel that if i start the dialog too fast that happens. Do you know what it can be related to?

**Closed** 2018-06-26 23:41 UTC
Labels: extensibility
