### ISSUE TITLE
No response to Add Connection on macOS

### ISSUE THREAD

**Issue by etherwizard** [Microsoft/sqlopsstudio#728] opened 2018-02-17 14:49 UTC
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:17:29.202Z)
- OS Version: Darwin x64 17.4.0
- Extensions: none
---

Steps to Reproduce:

1. Open SQL Operations Studio in macOS
2. Click on Add Connection

**Comment by samirbehara** [comment] 2018-02-17 17:12
Hello...I just installed the Feb Preview on my macOS and was able to see the Connection window after clicking on Add Connection. Can you quit SQL Ops Studio and try it again please?

**Comment by etherwizard** [comment] 2018-02-17 22:04
Version 0.26.7 (0.26.7)

Reopened. Getting the same result. No response to Add Connection. I also tried creating a server group, then right-clicking and selecting New Connection, and the New Connection button next to New Server Group.

**Comment by kburtram** [comment] 2018-02-20 17:15
@etherwizard could you please open the developer console `(Help -> Toggle Developer Tools, Console tab)` and let me know if there are any errors there?

**Comment by antonpiatek-imanage** [comment] 2018-02-27 08:39
Same issue seen on Ubuntu 17.10, installed via deb. Console tab shows nothing either

- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:33:40.686Z)
- OS Version: Linux x64 4.13.0-36-generic
- Extensions: none

**Comment by etherwizard** [comment] 2018-02-27 14:56
@kburtram: This is the error I see in the console:

_Activating extension `Microsoft.mssql` failed: Cannot find module '../resourceProvider/resourceProvider'._
_Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /private/var/folders/[etc]_

I am unable to install mssql using the Extensions Marketplace. It appears to be deactivated in this preview.

**Comment by vtomasr5** [comment] 2018-03-02 08:52
Hi
Same here but in my case the OS is Linux (Ubuntu 16.04 x64)
In a clean installation when I click on "Add Connection" there is no response (no new dialog and no errors)
I've check the Developer Tools console but nothing strange shows up.

After a while of clicking a few times in the "Add Connection" button something happened. The "Extension Host" crashed and new error messages show up in the Web Console:

[error.log](https://github.com/Microsoft/sqlopsstudio/files/1774306/error.log)

**Comment by kburtram** [comment] 2018-03-09 01:48
On various Linux systems you may need to install `libuwind8 ` manually for the .Net Core out-of-proc SQL Tools Service component to run (for example on Debian).  Please check if installing that library helps.

For Ubuntu, this component should already be installed in most configurations, so I'm not sure what's going on there.

We'll be updating the DEB and RPM packages to automatically pull in this dependency to avoid that issue.

**Comment by antonpiatek-imanage** [comment] 2018-03-09 08:02
Is `libuwind8` supposed to be a deb? Because on Ubuntu 17.10 apt doesn't know about it

**Comment by antonpiatek-imanage** [comment] 2018-03-14 08:18
Thanks @kburtram, looks like a typo above was what was confusing me - installing libunwind8 on my ubuntu 17.10 artful box now makes the connect dialog appear and I can successfully connect to a local db

**Comment by vtomasr5** [comment] 2018-03-14 12:01
Yeah, I can confirm that installing that package it works like a charm! :)

**Comment by etherwizard** [comment] 2018-04-04 14:32
@kburtram 

Any updates? Can we get the mssql extension bundled in the next preview for macOS? Or is there a way this extension can be copied to the app package manually?

**Comment by kburtram** [comment] 2018-04-04 15:17
@etherwizard `mssql` extension is bundled with SQL Ops Studio.  Are you still seeing this issue with March release `0.27.3`?

**Comment by etherwizard** [comment] 2018-04-04 15:32
@kburtram Thanks for following up. Yes, verified that version 0.27.3 is currently installed. The same error is being logged in the Developer Tools.

**Comment by etherwizard** [comment] 2018-04-26 05:17
These errors occur on opening immediately after clean install of 0.28.6 on macOS 10.13.4 (causes entire Electron window to be empty black with no user interaction possible):

> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251   ERR Cannot set property 'groupId' of undefined: TypeError: Cannot set property 'groupId' of undefined
>     at Function.ConnectionProfile.createFromStoredProfile (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:13931:47)
>     at file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:99870:62
>     at Array.map (native)
>     at ConnectionConfig.getConnections (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:99869:47)
>     at ConnectionStore.getConnectionProfileGroups (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:143714:66)
>     at ConnectionManagementService.getConnectionGroups (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:263923:42)
>     at ConnectionManagementService.hasRegisteredServers (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:263962:53)
>     at new ConnectionManagementService (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:263418:53)
>     at create (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:8492:14)
>     at InstantiationService._createInstance (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:92309:35)

> ERR [createInstance] MainThreadAccountManagement depends on UNKNOWN service accountManagementService.: Error: [createInstance] MainThreadAccountManagement depends on UNKNOWN service accountManagementService.
>     at InstantiationService._createInstance (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:92283:27)
>     at InstantiationService.createInstance (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:92270:29)
>     at ExtensionService._createExtensionHostCustomers (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:181963:59)
>     at file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:181924:39
>     at Object.notifySuccess [as _notify] (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15308:59)
>     at Object.enter (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:14990:30)
>     at _Base.Class.derive._creator._run (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15206:29)
>     at _Base.Class.derive._creator._completed (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15174:18)
>     at Object.notifySuccess [as _notify] (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15308:59)
>     at Object.enter (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:14990:30)

> [Extension Host] Activating extension 'Microsoft.account-provider-azure' failed: {1}.
> Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Activating extension `Microsoft.account-provider-azure` failed:  undefined
> Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Here is the error stack:  undefined
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Activating extension 'vscode.git' failed: {1}.
> Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Activating extension `vscode.git` failed:  undefined
> Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Here is the error stack:  undefined
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Activating extension 'vscode.merge-conflict' failed: {1}.
> Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Activating extension `vscode.merge-conflict` failed:  undefined
> Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Here is the error stack:  undefined
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Activating extension 'Microsoft.mssql' failed: Cannot find module './resourceProvider/resourceProvider'.
> Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251
> log @ workbench.main.js:24437
> ExtensionHostProcessWorker._logExtensionHostMessage @ workbench.main.js:177641
> (anonymous) @ workbench.main.js:177474
> ZoneDelegate.invokeTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:421
> Zone.runTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:188
> ZoneTask.invokeTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:496
> ZoneTask.ZoneTask.cancelFn.invoke @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:485
> emitTwo @ events.js:106
> emit @ events.js:194
> process.nextTick @ internal/child_process.js:766
> ZoneDelegate.invokeTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:421
> Zone.runTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:188
> ZoneTask.invokeTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:496
> ZoneTask.ZoneTask.cancelFn.invoke @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:485
> data.args.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:1316
> _combinedTickCallback @ internal/process/next_tick.js:73
> _tickCallback @ internal/process/next_tick.js:104
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Activating extension `Microsoft.mssql` failed:  Cannot find module './resourceProvider/resourceProvider'
> Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251
> log @ workbench.main.js:24437
> ExtensionHostProcessWorker._logExtensionHostMessage @ workbench.main.js:177641
> (anonymous) @ workbench.main.js:177474
> ZoneDelegate.invokeTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:421
> Zone.runTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:188
> ZoneTask.invokeTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:496
> ZoneTask.ZoneTask.cancelFn.invoke @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:485
> emitTwo @ events.js:106
> emit @ events.js:194
> process.nextTick @ internal/child_process.js:766
> ZoneDelegate.invokeTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:421
> Zone.runTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:188
> ZoneTask.invokeTask @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:496
> ZoneTask.ZoneTask.cancelFn.invoke @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:485
> data.args.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:1316
> _combinedTickCallback @ internal/process/next_tick.js:73
> _tickCallback @ internal/process/next_tick.js:104
> /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.…:2251 [Extension Host] Here is the error stack:  Error: Cannot find module './resourceProvider/resourceProvider'
> 	at Function.Module._resolveFilename (module.js:470:15)
> 	at Function.Module._load (module.js:418:25)
> 	at Function.load [as _load] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:44444:33)
> 	at Module.require (module.js:498:17)
> 	at Module.patchedRequire [as require] (/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
> 	at require (internal/module.js:20:19)
> 	at Object.<anonymous> (/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/mssql/out/main.js:23:28)
> 	at Object.<anonymous> (/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/mssql/out/main.js:165:3)
> 	at Module._compile (module.js:571:32)
> 	at Object.Module._extensions..js (module.js:580:10)

**Comment by etherwizard** [comment] 2018-05-11 02:06
These errors occur on opening immediately after clean install of 0.29.3 on macOS 10.13.4 (causes entire Electron window to be empty black with no user interaction possible):

>   ERR Cannot set property 'groupId' of undefined: TypeError: Cannot set property 'groupId' of undefined
    at Function.ConnectionProfile.createFromStoredProfile (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:13924:47)
    at file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:100472:62
    at Array.map (native)
    at ConnectionConfig.getConnections (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:100471:47)
    at ConnectionStore.getConnectionProfileGroups (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144499:66)
    at ConnectionManagementService.getConnectionGroups (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:265571:42)
    at ConnectionManagementService.hasRegisteredServers (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:265610:53)
    at new ConnectionManagementService (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:265066:53)
    at create (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:8426:14)
    at InstantiationService._createInstance (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:92749:35)
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [uncaught exception]: TypeError: Cannot set property 'groupId' of undefined
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 TypeError: Cannot set property 'groupId' of undefined
    at Function.ConnectionProfile.createFromStoredProfile (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:13924:47)
    at file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:100472:62
    at Array.map (native)
    at ConnectionConfig.getConnections (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:100471:47)
    at ConnectionStore.getConnectionProfileGroups (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144499:66)
    at ConnectionManagementService.getConnectionGroups (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:265571:42)
    at ConnectionManagementService.hasRegisteredServers (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:265610:53)
    at new ConnectionManagementService (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:265066:53)
    at create (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:8426:14)
    at InstantiationService._createInstance (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:92749:35)
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251   ERR [createInstance] MainThreadAccountManagement depends on UNKNOWN service accountManagementService.: Error: [createInstance] MainThreadAccountManagement depends on UNKNOWN service accountManagementService.
    at InstantiationService._createInstance (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:92723:27)
    at InstantiationService.createInstance (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:92710:29)
    at ExtensionService._createExtensionHostCustomers (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:183307:59)
    at file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:183268:39
    at Object.notifySuccess [as _notify] (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15301:59)
    at Object.enter (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:14983:30)
    at _Base.Class.derive._creator._run (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15199:29)
    at _Base.Class.derive._creator._completed (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15167:18)
    at Object.notifySuccess [as _notify] (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15301:59)
    at Object.enter (file:///Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:14983:30)
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 WARNING: Promise with no error callback:68
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 Object
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 Error: [createInstance] MainThreadAccountManagement depends on UNKNOWN service accountManagementService.
    at InstantiationService._createInstance (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:92723)
    at InstantiationService.createInstance (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:92710)
    at ExtensionService._createExtensionHostCustomers (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:183307)
    at /Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:183268
    at Object.notifySuccess [as _notify] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15301)
    at Object.enter (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:14983)
    at _Base.Class.derive._creator._run (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15199)
    at _Base.Class.derive._creator._completed (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15167)
    at Object.notifySuccess [as _notify] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:15301)
    at Object.enter (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:14983)
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] WARNING: Promise with no error callback:2
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host]% Object
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Activating extension 'Microsoft.account-provider-azure' failed: {1}.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Activating extension `Microsoft.account-provider-azure` failed:  undefined
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Here is the error stack:  undefined
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Activating extension 'vscode.git' failed: {1}.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Activating extension `vscode.git` failed:  undefined
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Here is the error stack:  undefined
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Activating extension 'vscode.merge-conflict' failed: {1}.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Activating extension `vscode.merge-conflict` failed:  undefined
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Here is the error stack:  undefined
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Activating extension 'Microsoft.mssql' failed: Cannot find module './resourceProvider/resourceProvider'.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Activating extension `Microsoft.mssql` failed:  Cannot find module './resourceProvider/resourceProvider'
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251
/Applications/SQL Operations Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2251 [Extension Host] Here is the error stack:  Error: Cannot find module './resourceProvider/resourceProvider'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.load [as _load] (/Applications/SQL Operations Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:44795:33)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/mssql/out/main.js:23:28)
	at Object.<anonymous> (/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/mssql/out/main.js:165:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)

**Comment by gscht** [comment] 2018-06-10 06:29
I got the same error. The hard disk was formatted with case-sensitive APFS.

After I formatted the disk with case-insensitive APFS, the error was gone.

macOS: 10.13.5
SQL Operations Studio: 0.29.3

**Comment by etherwizard** [comment] 2018-06-13 01:41
@gscht Thanks for reporting this! Unfortunately reformatting with APFS case-insensitive isn't an option for me. I wonder if this has anything to do with the default case-insensitive collation in SQL Server?

**Comment by kburtram** [comment] 2018-06-26 21:40
@etherwizard we're investigating a similar missing `resourceProvider` issue at https://github.com/Microsoft/sqlopsstudio/issues/1718.  I pushed a test build that may help with this issue https://sqlopsbuilds.blob.core.windows.net/stage/sqlops-macos-0.31.1-resourceprovider.zip.  Please let me know if you still hit this problem with this build.

**Comment by kburtram** [comment] 2018-06-27 18:41
There is a fix available for the `resourceProvider` issue on macOS with case-sensitive filesytems in the test build mentioned above.  This fix will be included in subsequent insiders and stable builds.  Please reactive if there are additional issues not resolved in those builds.

**Closed by kburtram** 2018-06-27 18:41 UTC
Labels: bug, connection, needs repro

**Comment by etherwizard** [comment] 2018-06-28 17:13
@kburtram: I can confirm that the test build linked in your post above is working correctly on macOS 10.13.5 with case-sensitive APFS. Many thanks for your attention to this!

**Comment by kburtram** [comment] 2018-06-30 23:14
@etherwizard thanks for confirming!  It's nice to finally close out this long standing bug.
