### ISSUE TITLE
Focus switches to results grid on return

### ISSUE THREAD

**Issue by jkreitzman** [Microsoft/sqlopsstudio#238] opened 2017-11-29 01:40 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:
1. Execute a query or statement that returns results.
2. When results are returned, focus is immediately switched to the results grid.

Expected Behavior:
1. Do not switch focus to the results grid...or provide a user-settable option.

I almost always execute a query or statement before it's finalized, to both check the validity of the logic I've written and validate the SQL. As a result, I'm still generally typing into the editor when results are returned and the focus is switched to the results grid.

**Comment by kburtram** [comment] 2017-11-29 21:03
@jkreitzman I'm close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/103.  We have this bug fixed in our internal repo for the Dec. release.

**Closed by kburtram** 2017-11-29 21:03 UTC

**Comment by jkreitzman** [comment] 2017-11-30 02:53
Ah, damn. I missed that one. Thanks.
