### ISSUE TITLE
Scrollbar position not retained when switching tabs

### ISSUE THREAD

**Issue by JesseKlaasse** [Microsoft/sqlopsstudio#914] opened 2018-03-15 15:56 UTC
- SQL Operations Studio Version: February preview (0.26.7)

Steps to Reproduce:
- Perform a query with enough results to require a scrollbar
- Scroll
- Open another tab and switch to it
- Go back to the original tab
- Scrollbar position has been reset

**Comment by kburtram** [comment] 2018-04-11 18:17
@JesseKlaasse  thanks for opening this issue.  I think this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/114.  Please reactive if there is tracking something else.

**Closed by kburtram** 2018-04-11 18:17 UTC
Labels: bug, query editor
