### ISSUE TITLE
Add support for PostgreSQL

### ISSUE THREAD

**Issue by insinfo** [Microsoft/sqlopsstudio#136] opened 2017-11-18 17:06 UTC
Add support for PostgreSQL

**Comment by Daylien** [comment] 2017-11-18 17:45
Please follow #56

**Comment by kburtram** [comment] 2017-11-18 19:00
@insinfo closing this as duplicate of #56.  Please upvote there so we can get an accurate gauge of interesting in this suggestion.  Thanks!

**Closed by kburtram** 2017-11-18 19:00 UTC
