### ISSUE TITLE
Right-click rows then select Create Insert Statements

### ISSUE THREAD

**Issue by mobsoftware** [Microsoft/sqlopsstudio#1687] opened 2018-06-20 16:20 UTC
Right-click rows then select Create Insert Statements

**Comment by kburtram** [comment] 2018-06-20 17:28
@mobsoftware I think this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/1194.  This is a really nice feature that we'd like to support in a future release.  Please reactivate if this is a different suggestion than https://github.com/Microsoft/sqlopsstudio/issues/1194.

**Closed by kburtram** 2018-06-20 17:28 UTC
Labels: query editor, suggestion

**Comment by mobsoftware** [comment] 2018-06-20 18:17
Thanks. It is a duplicate, I should have searched first.
