### ISSUE TITLE
Feature Request: Create indicator when saving result and when saving is finished

### ISSUE THREAD

**Issue by JohnyL** [Microsoft/sqlopsstudio#320] opened 2017-12-13 08:02 UTC
When saving result, there's no any progress indicator that saving is in progress and completed. For now, I have to refresh file manager's panel to monitor file's size - if it's increasing, then saving is still in progress.

**Comment by kburtram** [comment] 2018-04-13 01:09
I close as duplicate of https://github.com/Microsoft/sqlopsstudio/issues/316.

**Closed by kburtram** 2018-04-13 01:09 UTC
Labels: query editor, suggestion, ux
