### ISSUE TITLE
sqlSelect snippet - first tab is set to table name so no intellisense available

### ISSUE THREAD

**Issue by useless5** [Microsoft/sqlopsstudio#406] opened 2017-12-28 15:12 UTC
SQL Operations Studio Version: 0.24.1

Steps to Reproduce:

type sqlSelect into a new query window.
TableOrViewName is highlighted.
Start typing - no intellisense available because schema hasn't been specified yet

**Comment by kburtram** [comment] 2018-07-19 15:36
This looks like a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/226.  This is an interesting idea.

**Closed by kburtram** 2018-07-19 15:36 UTC
Labels: bug, snippet
