### ISSUE TITLE
Not displaying result-sets on multiple select (>=8)

### ISSUE THREAD

**Issue by Zenlil** [Microsoft/sqlopsstudio#1361] opened 2018-05-07 08:30 UTC
Issue Type: <b>Bug</b>

```
declare @x nvarchar(20) = 'openkeys'
select 'name1', * from sys.all_views where [name] = @x
select 'name2', * from sys.all_views where [name] = @x
select 'name3', * from sys.all_views where [name] = @x
select 'name4', * from sys.all_views where [name] = @x
select 'name5', * from sys.all_views where [name] = @x
select 'name6', * from sys.all_views where [name] = @x
select 'name7', * from sys.all_views where [name] = @x
select 'name8', * from sys.all_views where [name] = @x
```
When running this I only get the resultset on 1 and 2, the remaining (3 to 8) are empty
When running all but the last one I get the resultset on all 7

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|15.84GB (6.40GB free)|
|Process Argv|C:\Apps\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by kminnihan** [comment] 2018-05-11 11:40
I am having this very same issue and it is preventing me from developing with this tool.  Please provide advice on how to resolve this issue.

**Comment by kburtram** [comment] 2018-08-07 23:09
I'm going to close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/156 so we can track this work in one place.  Please leave related feedback in https://github.com/Microsoft/sqlopsstudio/issues/156.

**Closed by kburtram** 2018-08-07 23:09 UTC
Labels: bug, feature gap, query editor
