### ISSUE TITLE
Script as Create/Alter/Drop opens a tab that's not connected to the source DB

### ISSUE THREAD

**Issue by xelossan** [Microsoft/sqlopsstudio#1561] opened 2018-06-06 09:32 UTC
Issue Type: <b>Bug</b>

1. Connect to some DB
2. Right click -> New query - opens a new tab connected to the DB
3. Expand Tables or Views
4. Right click -> Script as Create (or Alter or Drop) - opens a new tab that is not connected to the DB, so in order to actually alter w view for example, I need to connect manually

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|Memory (System)|5.89GB (0.37GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by anthonydresser** [comment] 2018-06-07 15:33
dupe of #825

**Closed by anthonydresser** 2018-06-07 15:33 UTC
