### ISSUE TITLE
Go not working

### ISSUE THREAD

**Issue by Gagansharmaonly** [Microsoft/sqlopsstudio#186] opened 2017-11-22 07:24 UTC
- SQL Operations Studio Version:

Steps to Reproduce:
IN SSMS versions Query for loop is working as given below, but in SQL Operations Studio I think this is missing.

Query example: 
go
select 1 as A
go 10

**Comment by kevcunnane** [comment] 2017-11-22 07:32
This is a duplicate of #42, I’ll close this as we’re tracking the feature there. I actually just implemented and it’s out for review so it’ll be supported in the next release.

**Closed by kevcunnane** 2017-11-22 07:32 UTC
