### ISSUE TITLE
objects in tempdb have incorrect highlighting

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/sqlopsstudio#142] opened 2017-11-18 23:01 UTC
- SQL Operations Studio Version:

Steps to Reproduce:
Enter: CREATE TABLE #foo (bar int);

Everything from the number sign (hash for the UK) is green, but should be the same colors as;
CREATE TABLE foo (bar int);

**Comment by abist** [comment] 2018-02-01 18:50
Duplicate of https://github.com/Microsoft/sqlopsstudio/issues/98

**Closed by abist** 2018-02-01 18:50 UTC
Labels: bug, intellisense
