### ISSUE TITLE
Object scripting failed

### ISSUE THREAD

**Issue by jeffest** [Microsoft/sqlopsstudio#88] opened 2017-11-16 17:25 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

I'm connected to a server with 100+ databases and using a database with 6000+ stored procs

Steps to Reproduce:

1. Right click a stored procedure
2. Select 'Script as create'

What I got :
![sqloperation_scriptingfailed](https://user-images.githubusercontent.com/9037132/32905852-77b96dc0-cafb-11e7-9f93-b7c6eadf87e8.png)

What I expect:
The procedure create script

**Comment by llali** [comment] 2017-11-22 22:02
This is a duplicate of #177

**Closed by llali** 2017-11-22 22:02 UTC
Labels: bug, scripting

**Comment by jeffest** [comment] 2017-11-23 14:13
How come #177 would not be a duplicate of this instead?? It was created after mine !!!
Just kidding...

Thank you for your hard work.

**Comment by llali** [comment] 2017-11-27 16:51
Hi @jeffest sorry about that :)

I tried to close the duplicate ones to make sure I verified all the issues.  This bug and #177 are both because of the same bug which I fixed and will be in the next release.
