### ISSUE TITLE
Feature Request: Generate Inserts From Results

### ISSUE THREAD

**Issue by Calidus** [Microsoft/sqlopsstudio#1194] opened 2018-04-20 14:31 UTC
Being able to generate INSERT scripts from the results view would be very useful when the use of SELECT INSERT statements isn't possible.

**Comment by kburtram** [comment] 2018-07-20 15:56
I think click a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/459.  Please reactive if this is different, or leave additional comments in that suggest.

**Closed by kburtram** 2018-07-20 15:56 UTC
Labels: query editor, suggestion
