### ISSUE TITLE
Cannot attach to SQL Server that uses an alias. 

### ISSUE THREAD

**Issue by seanbamforth** [Microsoft/sqlopsstudio#838] opened 2018-03-05 10:36 UTC
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Create an alias in sql server configuration manager. 
2. Try and attach to this alias name.

**Comment by kburtram** [comment] 2018-04-13 01:50
Closing as duplicate of https://github.com/Microsoft/sqlopsstudio/issues/71.  Thanks for the suggestion!

**Closed by kburtram** 2018-04-13 01:50 UTC
Labels: connection, suggestion
