### ISSUE TITLE
Script to alter does not automatically connect

### ISSUE THREAD

**Issue by cstech-carlcamilleri** [Microsoft/sqlopsstudio#2167] opened 2018-08-07 13:42 UTC
- SQL Operations Studio Version:
0.31.4
Steps to Reproduce:
1. Alter stored procedure from the servers toolbar or by pressing F12
2. Stored procedure gets scripted in a new query window but does not retain the connection (and database)

**Comment by kburtram** [comment] 2018-08-07 18:58
@cstech-carlcamilleri thanks for the suggestion.  This looks like a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/825 which is resolved in the latest `insider` build at https://github.com/Microsoft/sqlopsstudio/releases.

**Closed by kburtram** 2018-08-07 18:58 UTC
