### ISSUE TITLE
mssql: SQL Tools Service component exited unexpectedly. Please restart SQL Operations Studio.

### ISSUE THREAD

**Issue by chrismovie** [Microsoft/sqlopsstudio#492] opened 2018-01-16 16:07 UTC
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1.
2.

**Comment by kburtram** [comment] 2018-01-16 17:45
@chrismovie this is a generic message when the out-of-proc service component crashes.  Do you happen to have repo steps, or other details that would help isolate the cause of the crash?

**Comment by kburtram** [comment] 2018-01-17 20:42
@chrismovie I'm going to close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/286.  Please reactive if you can provide additional repro details to disambiguate this from the other issue.  Thanks!

**Closed by kburtram** 2018-01-17 20:42 UTC
Labels: bug, more info
