### ISSUE TITLE
I would like to be able to open .sql files and have it automatically connect to an instance

### ISSUE THREAD

**Issue by LitKnd** [Microsoft/sqlopsstudio#2141] opened 2018-08-03 18:23 UTC
Issue Type: <b>Feature Request</b>

In Explorer, I can view a folder full of .sql files, which is nice.

However, for each file I open, I have to manually connect to an instance.

As a presenter, I often have a series of scripts that I want to step through for an instance. Having a script automatically connect to the last instance I connected to makes this process much more smooth: currently the only way I've found to do this in Ops Studio requires a bit of mousing around and it looks a bit sloppy.

In SSMS, when "File, Open" is used to open a new file, it will automatically connect to the "active" instance, so I believe an automatic connection behavior for files opened in Explorer would feel natural to most users moving over.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T01:53:50.812Z)
OS version: Darwin x64 17.7.0

**Comment by kburtram** [comment] 2018-08-03 20:38
@LitKnd thanks for the suggestion!  I believe this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/641.  Please reactive if this is a different issue.

**Closed by kburtram** 2018-08-03 20:38 UTC
Labels: suggestion
