### ISSUE TITLE
html content in columns breaks grid

### ISSUE THREAD

**Issue by tekken22** [Microsoft/sqlopsstudio#1971] opened 2018-07-19 14:43 UTC
Issue Type: <b>Bug</b>

html content in columns breaks grid

![image](https://user-images.githubusercontent.com/36925936/42949779-8548a360-8b40-11e8-918e-9be0e0f4891a.png)

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2623 v4 @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.79GB free)|
|Process Argv|D:\3partyPrograms\micrsosft\sqlops\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment] 2018-07-19 17:08
@anthonydresser do you know what's going on here?  Did we miss somewhere that we need to add an `escape`

**Comment by kburtram** [comment] 2018-07-19 17:13
@tekken22 do you know the data type of the column that contains the HTML?  Is it a string field?

**Comment by anthonydresser** [comment] 2018-07-19 18:23
The only character we aren't escaping is ' which shouldn't matter since we don't see that anywhere for it to mess with. Would be interesting to see the content that causes this.

**Comment by kburtram** [comment] 2018-07-19 21:42
@tekken22 I published a test build containing #1974 at https://sqlopsbuilds.blob.core.windows.net/stage/sqlops-windows-0.32.1-escape.zip.

That PR contains our best guess at what may be happening here.  Please test it out in your scenario if you have a chance.

If that doesn't work we'd like to try to track down what's happening here if possible.  We made some accessibility updates in this release that add more extensive aria tags.  One issue we've run into in a few places is that the content in the aria string is not properly being escaped for some reason.  Unfortunately, without knowing the cell content it's hard to know why the escape method is failing.

When I recently investigated a couple similar issues I used  `Developer Tools` `Element Inspector` to see why the aria label was messed up.  Basically, if you open the Developer Tools and click the arrow in the Elements pane then click the cell element that contains the problematic content, then you can typically see the problem by looking at the `aria-label` of the cells parent `div`.  This information would be really helpful to root cause this issue.

![image](https://user-images.githubusercontent.com/599935/42971578-b4dbdfc2-8b61-11e8-8cf6-9e8e002a5f21.png)

**Comment by tekken22** [comment] 2018-07-20 12:05
this will reproduce, looks like single quote is the issue:

`select 'ATTENTION: <span class="param" contenteditable="false">[FirstName]</span>&nbsp; &nbsp;<span class="param" contenteditable="false">[LastName]</span>''s
<span class="param" contenteditable="false">[Type_of_Request]</span>&nbsp;Request 
is submitted' as 'subject'  into #sqlopstest 

select * from #sqlopstest `

**Comment by kburtram** [comment] 2018-07-20 14:46
@tekken22 thanks!  I verified the repro and confirmed the test build doesn't resolve the problem.  We'll work on a fix today.

**Comment by kburtram** [comment] 2018-07-21 02:32
@tekken22 the repro scenario is fixed in the latest insiders build at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.1 and the fix will be included in the August stable release next month.  Thanks for the clear repro script!

Please reactive if you continue to hit this issue.

![screen](https://user-images.githubusercontent.com/599935/43031280-71f86570-8c53-11e8-86dc-97ad445fc292.png)

**Comment by anthonydresser** [comment] 2018-08-30 17:51
We could make a special release on slickgrid for this release, but probably just equivalent to just taking an earlier release.

**Comment by kburtram** [comment] 2018-08-30 21:34
This should be fixed in https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.8.  Please reactive if the problem persists in the latest build.

**Closed by kburtram** 2018-08-30 21:34 UTC
Labels: bug, query editor, regression
