### ISSUE TITLE
No script was returned when scripting as Create on object StoredProcedure

### ISSUE THREAD

**Issue by SebastianPfliegel** [Microsoft/sqlopsstudio#187] opened 2017-11-22 09:15 UTC
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:

- Create a Procedure with two spaces between CREATE and PROCEDURE
```sql
CREATE  PROCEDURE [dbo].[test_proc]
AS
SELECT 1
```
- In Object Explorer right click an existing stored procedure and select 

As a result you'll receive the message "No script was returned when scripting as Create on object StoredProcedure". As soon as I remove the second space between CREATE/ALTER and PROCEDURE it works fine.

**Comment by llali** [comment] 2017-11-22 22:02
This is a duplicate of #177

**Closed by llali** 2017-11-22 22:02 UTC
Labels: scripting
