### ISSUE TITLE
Add check for updates in file or help menu on MacOS

### ISSUE THREAD

**Issue by SimonSays13** [Microsoft/sqlopsstudio#503] opened 2018-01-17 12:49 UTC
- SQL Operations Studio Version: 0.24.1

**Comment by kburtram** [comment] 2018-01-17 16:57
@SimonSays13 I'm going to close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/481.  The 0.25.4 release includes the necessary product changes to support auto-update in Feb (...we haven't been able to test end-to-end yet, but this is our current plan).

**Closed by kburtram** 2018-01-17 16:57 UTC
