### ISSUE TITLE
CTRL + N shortcut does not allow database selection

### ISSUE THREAD

**Issue by RobbuOmnichannel** [Microsoft/sqlopsstudio#422] opened 2018-01-03 12:42 UTC
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. When we have more than one server group and press "CTRL + N" a new "New Query" tab is opened, but it is impossible to select the server / database. Even if the shortcut runs with a selected SQL server.

**Comment by SebastianPfliegel** [comment] 2018-01-03 15:03
Currently everytime you create a new query tab no connection will be established. You have to do this yourself buy using either the `Run` or `Connect` button. If you want a connection to be established whenever you create a new tab you need to wait for #6 to be solved (which is on the current agenda/milestone).

**Comment by SebastianPfliegel** [comment] 2018-01-03 15:05
Another workaround is to right-click a database or server and select `New Query`. This creates a new tab and connects to the server.

**Comment by thiagothamiel** [comment] 2018-01-03 15:21
Exactly that, but it's a bug.
If I have a database selecting the expected behavior is the same as the "microsoft sql server manager studio"

**Comment by kburtram** [comment] 2018-01-03 23:01
I'm going to close this as a duplicate of #6 to keep the discussion consolidated to a single issue.  We don't currently have the concept of a "current connection" to use for global commands like Ctrl-N.  For example, if a user is currently interacting with the dashboard with a particular database, but happens to have the cursor positioned on a particular Object Explorer node, then runs Ctrl-N should we use the connection context from OE or the dashboard?  In any case, we're looking at the various use cases here and will fix this in an upcoming release.

**Closed by kburtram** 2018-01-03 23:01 UTC
