### ISSUE TITLE
Horizontal scroll missing on results

### ISSUE THREAD

**Issue by peterox** [Microsoft/sqlopsstudio#1589] opened 2018-06-08 05:19 UTC
Issue Type: <b>Bug</b>

Run a query returning lots of columns.
The Results and Messages areas are populated
You cannot scroll the results to see more column data until you minimise the messages area

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|15.88GB (4.70GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
Reproduces without extensions

**Comment by kburtram** [comment] 2018-06-12 17:08
@peterox I wasn't able to repro this issue.  I know we've gotten previous feedback that the we sometime get "double scrollbars" (as shown below) which is often easy to overlook, and can cause a situation similar to what you've described.  Can you confirm if the issue is the double scrollbar UX problem, or a separate bug?  Thanks! 

![screen](https://user-images.githubusercontent.com/599935/41305672-782846c0-6e28-11e8-824d-dbe570612082.png)

**Comment by kburtram** [comment] 2018-06-19 00:38
Closing based on the previous comment.  Please reactive if this issue persists.

**Closed by kburtram** 2018-06-19 00:38 UTC
Labels: more info, query editor

**Comment by peterdivvito** [comment] 2018-06-20 09:46
Hi there. The issue is with the horizontal scroll bar, to scroll to the right when the number of columns is larger than the window width.

**Comment by peterox** [comment] 2018-06-20 09:52
Hi @kburtram,

The issue is with the horizontal scroll bar at the bottom of the results list, not the vertical to the right.

As you can see in your screen shot, you can't see the scroll bar at the bottom of the results. If you close the Messages view then you can access the scroll bar.

I am unable to re-open this issue

Cheers,
Peter
