### ISSUE TITLE
Copy with Headers, repeating header

### ISSUE THREAD

**Issue by dhsipe** [Microsoft/sqlopsstudio#2373] opened 2018-08-30 15:04 UTC
Issue Type: <b>Bug</b>

Run query that returns rows in the results grid.   Right click on the results grid click 'Select All'    Then right Click and click 'Copy with Headers'  then paste into Excel.

The header rows is display every other row, not just on the top.  

Sometimes the copy does not work at all.  

This was working prior to the release I updated today.

SQL Operations Studio version: sqlops 0.32.7 (b3766d7421bac5d8596eb2ce4980da5546325282, 2018-08-30T02:59:53.029Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.16GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment] 2018-08-30 15:49
Closing as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/2372.  We'll have a fix for this issue later today.

**Closed by kburtram** 2018-08-30 15:49 UTC
