### ISSUE TITLE
Server Name and Server Path

### ISSUE THREAD

**Issue by rsmolkin** [Microsoft/sqlopsstudio#430] opened 2018-01-03 21:30 UTC
- SQL Operations Studio Version:0.24.1

When creating a new connection, it would be nice is the Server Name could be a "friendly server name" as in what gets displayed in the list under DB groups later, instead of a long URI path to AWS or an IP address.  This make is pretty hard to figure out which is which and to fit the full path.

Then you could have a different text box for collecting the actual server IP or URI...

![image](https://user-images.githubusercontent.com/28454845/34540674-67321ae2-f0a3-11e7-9042-14ad2273b96f.png)

![image](https://user-images.githubusercontent.com/28454845/34540691-779edd20-f0a3-11e7-825c-4e6195fb4c14.png)

**Comment by erickangMSFT** [comment] 2018-01-11 20:58
@rsmolkin This request is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/66 This request will be addressed.

**Closed by erickangMSFT** 2018-01-11 20:58 UTC
Labels: connection, suggestion
