### ISSUE TITLE
Active directory MFA support

### ISSUE THREAD

**Issue by r4ndom4is** [Microsoft/sqlopsstudio#1506] opened 2018-05-28 12:29 UTC
Issue Type: <b>Feature Request</b>

Cannot connect to azure dw because no MFA support

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.17134

**Comment by wilsonge** [comment] 2018-05-29 08:55
Duplicate of https://github.com/Microsoft/sqlopsstudio/issues/13

**Closed** 2018-05-29 13:35 UTC
