### ISSUE TITLE
No response while clicking Add Connection button.

### ISSUE THREAD

**Issue by haixinlin** [Microsoft/sqlopsstudio#1117] opened 2018-04-11 03:35 UTC
- SQL Operations Studio Version: sqlops 0.27.3 (9474415ad68b5a70e8b851698c8c836664a9d5b5, 2018-03-27T05:34:58.705Z)
- OS Version: Darwin x64 17.5.0
- Extensions: none
---

Steps to Reproduce:

1. Open sqlops
2. Click Add Connection button
3. Nothing happened.

**Comment by haixinlin** [comment] 2018-04-12 00:40
It seems I've got no response from running the specific command, like below



xin-rmbp:1.4.0-alpha.16 haixinlin$ pwd

/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/1.4.0-alpha.16

xin-rmbp:1.4.0-alpha.16 haixinlin$ ./MicrosoftSqlToolsServiceLayer









And do I have to install .Net Core 2.0 before I run the application? I've not installed it on this computer yet.








At 2018-04-12 08:19:17, "Karl Burtram" <notifications@github.com> wrote:


@haixinlin we've had a couple reports of similar behavior on macOS, but we still don't have an internal repro or additional diagnostic information. I suspect there is something regarding the environment that is causing issues with .Net Core 2.0.

If you have time, could you please try running the below command from a terminal window. The app should start without any output. You can close the process with Control+C.

"/Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/1.4.0-alpha.20/MicrosoftSqlToolsServiceLayer"


Please replace /Applications/SQL Operations Studio.app/ with the location that SQL Ops Studio is installed

Please let me know if any error messages are omitted when running the above command. Thanks!

**Comment by kburtram** [comment] 2018-04-12 00:54
@haixinlin to clarify, when you ran the application it exited immediately without any output?

We shouldn't need to install .Net Core 2.0 to run the application.  Though if the application is exiting immediately there is probably something related to .Net Core compatibility that's triggering the issue.

If you have time and the inclination, it could be helpful to try to install the .Net Core SDK and build a little test app following steps 1-3 at https://www.microsoft.com/net/learn/get-started/macos.  

Any errors you hit during that process may provide some details that would help diagnosis what's going on.  I understand if this is a bit more involved then you'd like to get for this issue :smile:.  Thanks!

**Comment by kburtram** [comment] 2018-04-16 18:38
@haixinlin I'm going to close this as a duplicate of #728.  Please reactive if you have a chance to help further diagnosis, or if you prefer please add additional content directly in #728.  Thanks!

**Closed by kburtram** 2018-04-16 18:38 UTC
Labels: bug, more info
