### ISSUE TITLE
result data with single quote in varchar max

### ISSUE THREAD

**Issue by mcneely6071** [Microsoft/sqlopsstudio#2287] opened 2018-08-22 02:34 UTC
- SQL Operations Studio Version:
0.31.4
Steps to Reproduce:
Populate a varchar max field with minified json string that has single quotes in it such as
 [[{"whyWouldYou" :"don't do this example, it will break"}],[{"anotherThing": "just for giggles no single quotes"}]]
 using completely valid sql escaping/ not SQLOS
SELECT that record from SQLOS

i have data that works fine when using the plug in for VS code, as well as showing up fine SSMS but it pops out of its intended grid in SQLOS i would guess it is something to do with the way the results window is coded....but i would also have expected that to be the same or very similar to VSCode....exact same data looks fine there

**Comment by kburtram** [comment] 2018-08-22 04:36
@mcneely6071 thanks for opening the bug.  I think this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/2086 and should be fixed in the latest insiders build at https://github.com/Microsoft/sqlopsstudio/releases.  Please reactive if you still hit the issue on the latest builds.

**Closed by kburtram** 2018-08-22 04:36 UTC
