### ISSUE TITLE
git icon not available

### ISSUE THREAD

**Issue by umar86** [Microsoft/sqlopsstudio#706] opened 2018-02-15 10:03 UTC
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. navigate to source control tab
2. find the git icon to connect to a git controlled folder
Icon not available!

**Comment by umar86** [comment] 2018-02-15 10:28
Available from the Explorer Cntrl+ Shift +E, but cant commit , compare etc

**Comment by kburtram** [comment] 2018-02-16 01:55
@umar86 I checked the Feb Public Preview (0.26.6) build and as far as I can tell we match current VS Code source control behavior.  Basically I see the following.

1. Open a folder that is currently under Git source control and the Git viewlet is populated with SCC content (diffs, push, pull, branches, etc).
2. Open a folder that is not under Git source control and the Git viewlet is empty except a Git icon is present in the top left that allows initializing a Git repo for the folder.
3. Go to Git viewlet without a folder open and the Git viewlet is empty with no Git icon.

Scenario 3 matches your description, but would be by design since SCC requires an active folder or workspace.  Please let me know if your experiencing an issue not covered above.

**Comment by kburtram** [comment] 2018-03-07 00:51
Closing based on previous response.  Please reactivate if this is still an issue.

**Closed by kburtram** 2018-03-07 00:51 UTC
Labels: more info
