### ISSUE TITLE
The servers tab collapses all connections and folders when you X out of a search.

### ISSUE THREAD

**Issue by matneyx** [Microsoft/sqlopsstudio#331] opened 2017-12-15 18:22 UTC
- SQL Operations Studio Version:
0.23.6

**Steps to Reproduce:**
1. Connect to a server in the servers tab
2. Drill down to an object in the folders (Server -> Tables -> Object)
3. Use the "Search server names" textbox to search for a server, including the one you're connected to
4. Click the X to clear search results

**Expected Results**
Search should clear, and previous state -- including open server and folders -- should appear.

**Actual Results**
Search box clears, and all available servers appear but previously open folders and such are now closed.

**Comment by abist** [comment] 2017-12-18 22:39
Duplicate of https://github.com/Microsoft/sqlopsstudio/issues/73

**Closed by abist** 2017-12-18 22:39 UTC
Labels: bug
