### ISSUE TITLE
"GUID should contain 32 digits with 4 dashes" error when connecting

### ISSUE THREAD

**Issue by XpertDBA** [Microsoft/sqlopsstudio#1896] opened 2018-07-11 14:08 UTC
- SQL Operations Studio Version:

Already had this as a previous issue and it was never resolved it for us.  I gave up trying eventually.

https://github.com/Microsoft/sqlopsstudio/issues/198 

Steps to Reproduce:

Install the latest June version of SQLOPS, execute it and enter a known server with known Windows Authentication (which we currently use for SQL Server Management Studio).  

Get the error message:

GUID should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)

**Comment by kevcunnane** [comment] 2018-07-11 15:39
Thanks for including the call stack! I've opened a PR to fix this https://github.com/Microsoft/sqltoolsservice/pull/654. @kburtram any idea when we'll pick up an updated SqlToolsService? If we include in an upcoming Insiders build we could test if this fixes the issue for these users.

**Comment by XpertDBA** [comment] 2018-07-11 16:46
What does this CLOSED message mean for us?

**Comment by kburtram** [comment] 2018-07-11 16:56
@XpertDBA the issue is closed automatically when a Pull Request is merged that has a proposed fix for an issue.  In this case, the fix is going into a dependent project and will need to be separately integrated into this project, and then the fix should be available in the next build.  I'll reopen the issue until we're able to verify the fix.

@kevcunnane I've been updating the toolsservice once or twice a week recently as needed to pickup fixes.  Generally we ask people making fixes in the toolsservice to integrate the toolsservice update into this project if there is a desire to have the fix picked up on any particular schedule.

**Comment by LBremseth** [comment] 2018-07-17 20:09
@XpertDBA @kburtram @kevcunnane just wanted to confirm that this appears to have fixed the issues we were seeing using SQL Operations Studio in our environment.  I've installed build 0.31.3 and no longer receive the "GUID should contain 32 digits with 4 dashes" error.

**Comment by kburtram** [comment] 2018-07-21 18:03
@LBremseth the July Public Preview contains this fix and is available at https://github.com/Microsoft/sqlopsstudio/releases/tag/0.31.4.  Thanks for verifying the fix.

**Closed by kburtram** 2018-07-21 18:03 UTC
Labels: bug
