### ISSUE TITLE
Allow reordering of connections within Server group

### ISSUE THREAD

**Issue by psimoneau22** [Microsoft/sqlopsstudio#335] opened 2017-12-16 13:36 UTC
- SQL Operations Studio Version:  0.23.6

Steps to Reproduce:

1: Create a server group
2: Add multiple connections to the server group
3:  Cannot change order of connection within group connection list

Allow drag and drop to move up/down a connection within the server group.

**Comment by kburtram** [comment] 2018-07-16 17:30
Closing as duplicate of https://github.com/microsoft/sqlopsstudio/issues/167.  Please leave additional comments there to capture the scenario.

**Closed by kburtram** 2018-07-16 17:30 UTC
Labels: feature gap, object explorer, suggestion
