### ISSUE TITLE
WMIC error on startup.

### ISSUE THREAD

**Issue by DanwithArduino** [Microsoft/sqlopsstudio#2101] opened 2018-07-31 19:44 UTC
- SQL Operations Studio Version: 0.32.2 (but it has been happening with the last two stable releases as well)

Steps to Reproduce:
Occurs immediately after initial launch of the program. I am running the following extensions: SQL Server agent, SSMS Keymap. I am using version control through GIT GUI. Ru
![image](https://user-images.githubusercontent.com/10458867/43483092-99b2c802-94d8-11e8-9cb1-44988103c484.png)

edit: windows 7 64bit

**Comment by kburtram** [comment] 2018-07-31 19:59
@DanwithArduino there's some code that tries detect where the system is 32-bit or 64-bit using wmic.exe.  Maybe this error is Win7-specific or something.

Do you know if the path in error message is referring to valid file?  On my system the exe is at `C:\Windows\System32\wbem\WMIC.exe`

**Comment by DanwithArduino** [comment] 2018-08-20 13:57
Is there anything I can do to provide any more information on this error?

**Comment by kburtram** [comment] 2018-08-20 18:35
@DanwithArduino sorry for delay.  Could you please confirm if you have a file at `C:\Windows\System32\WMIC.exe`?  i.e., without the `wbem` component of the path.

It seems like SQL Ops Studio is trying to run the program from there.  Also, if you run "wmic.exe" from the global run dialog box (Windows Key+R) what happens?  

From the error message I'm guessing there is a non-executable file with the name "wmic.exe" on the path prior to the `C:\Windows\System32\wbem` directory.

**Comment by DanwithArduino** [comment] 2018-08-20 20:03
![image](https://user-images.githubusercontent.com/10458867/44363508-5ef38c00-a492-11e8-848e-72e4b04ffd4c.png)



Indeed, the one that resides in my system32 folder, but not the wbem sub folder, may be the issue... 
![image](https://user-images.githubusercontent.com/10458867/44363588-995d2900-a492-11e8-9d64-60716427c119.png)

Running from the run dialog does indeed pop the same error.

**Comment by kburtram** [comment] 2018-08-20 20:11
@DanwithArduino you should be able to resolve this issue by either (1) removing the invalid wmic.exe from your path or (2) reordering your path such that `C:\Windows\System32\wbem` is ahead of `C:\Windows\System32`.  

I'll close this issue now since it looks like the problem is understood.  Please let me know if there are additional questions I can help with.

**Closed by kburtram** 2018-08-20 20:11 UTC
Labels: bug, more info, shell
