### ISSUE TITLE
Scroll position is lost when changing between tabs

### ISSUE THREAD

**Issue by luismiguelgilbert** [Microsoft/sqlopsstudio#1123] opened 2018-04-11 17:53 UTC
- SQL Operations Studio Version:
0.27.3

- Problem:
Scroll position in results grids is lost when changing between tabs

Steps to Reproduce:
- Open 2 tabs
- Execute queries on each tab.
- Go to first tab and scroll down in results.
- Go to second tab
- Return to first tab. At this point, scroll position is at top. It doesn't stay on its last position

**Comment by kburtram** [comment] 2018-04-11 18:17
@luismiguelgilbert thanks for opening this issue.  I think this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/114.  Please reactive if there is tracking something else.

**Closed by kburtram** 2018-04-11 18:17 UTC
