### ISSUE TITLE
LineBreaks Not Honored in ResultSet

### ISSUE THREAD

**Issue by kgeorge314** [Microsoft/sqlopsstudio#2128] opened 2018-08-02 16:46 UTC
Issue Type: <b>Bug</b>

When you execure the below and copy the resultset - it flattens the text. This a problem when trying to generate DySQL-ish snippets. 
```
SELECT N'
This 
is 
a 
multi-line 
select
' as a MultiLineStatement
```

_Similarly_ 
```
SELECT 
N'This'         +CHAR(10)+CHAR(13)+
N'is'           +CHAR(10)+CHAR(13)+
N'a'            +CHAR(10)+CHAR(13)+
N'multi-line'   +CHAR(10)+CHAR(13)+
N'select'
```
If you copy the (either) above Result you get `This is a multi-line select` vs 
```
This 
is 
a 
multi-line 
select
```

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (4.27GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-search|Red|0.2.1

</details>

**Comment by kburtram** [comment] 2018-08-03 20:35
@jdalton thanks for reporting this bug.  I think this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/336.  Please add additional notes on that issue, or reactive if this is a separate issue.

**Closed by kburtram** 2018-08-03 20:35 UTC

**Comment by kgeorge314** [comment] 2018-09-06 10:07
Hi @kburtram, yes it is a duplicate. I should have broadened my search before creating it :)
