### ISSUE TITLE
Edit Data does not support filtering or sorting

### ISSUE THREAD

**Issue by juanfhoyo** [Microsoft/sqlopsstudio#302] opened 2017-12-07 10:50 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:
Data editor does not allow to change the select or order.

**Comment by erickangMSFT** [comment] 2017-12-07 16:48
@juanfhoyo Edit data feature is in early preview form. Please keep filing issues / suggestions in that feature area. [help wanted]

**Comment by thesmallbang** [comment] 2018-03-17 20:05
This is huge. It is the biggest reason why I can't switch to this as my day to day over SSMS

**Comment by kburtram** [comment] 2018-04-06 23:35
Closing as duplicate of #78.  @corivera is currently implementing this feature by adding a SQL editor to the edit data document.

**Closed by kburtram** 2018-04-06 23:35 UTC
Labels: edit data, suggestion
