### ISSUE TITLE
Some results don't display, others appear/disappear while scrolling

### ISSUE THREAD

**Issue by KyleStay** [Microsoft/sqlopsstudio#1021] opened 2018-03-28 20:41 UTC
- SQL Operations Studio Version: sqlops 0.27.3 (9474415ad68b5a70e8b851698c8c836664a9d5b5, 2018-03-27T05:25:59.481Z)
- OS Version: Windows_NT x64 10.0.10240
- Extensions: none
---
## Other notes:

I started noticing this issue after using ~10 different select statements. Sometimes results never display in SQL Operations Studio but will be displayed in Excel if a CSV is saved. The Messages section says the correct number of results even if no results are showing in the Results section. This is a deal breaker for me if SQL Operations Studio doesn't reliably display results.

Steps to Reproduce:

1. Query using ~25 different select statements using a variable and sub-queries on tables with 6 - 60 columns of varchar, int, money, datetime, and timestamp data with between 0 and 12 (approximate) records returned per select statement
2. Scroll through results, notice that some disappear/appear depending on where you are scrolling.

**Comment by dermeister0** [comment] 2018-07-13 07:15
I experience the bug since the first preview. Still not fixed in 0.30.6.

**Comment by kburtram** [comment] 2018-08-22 03:39
Closing as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/156.  We're currently working on this issue for September.

**Closed by kburtram** 2018-08-22 03:39 UTC
Labels: bug, feature gap, query editor
