### ISSUE TITLE
Counter column (Improvement)

### ISSUE THREAD

**Issue by bmaximus91** [Microsoft/sqlopsstudio#705] opened 2018-02-15 08:28 UTC
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 6.3.9600
---

Steps to Reproduce:

1. Counter column on the left of the results should be frozen, like SQL Management Studio, this helps a lot selecting multiple rows while having many columns. 

Friendly 
Thanks

**Comment by kburtram** [comment] 2018-04-13 01:12
I'll close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/412.  Thanks!

**Closed by kburtram** 2018-04-13 01:12 UTC
Labels: suggestion
