### ISSUE TITLE
Modify edit query

### ISSUE THREAD

**Issue by josh890** [Microsoft/sqlopsstudio#402] opened 2017-12-27 13:57 UTC
- SQL Operations Studio Version: 0.24.1

**As a user I want to** modify Edit Data query to add filtering and joins for large tables **to be able to** manage datasets with large amount of data (or ones with complicated FK entries)

**Comment by erickangMSFT** [comment] 2018-01-11 21:41
related: https://github.com/Microsoft/sqlopsstudio/issues/302

**Comment by thesmallbang** [comment] 2018-03-17 20:05
This is huge. It is the biggest reason why I can't switch to this as my day to day over SSMS

**Comment by ScottRFrost** [comment] 2018-04-05 13:47
Duplicate of #78 , #302 .  This can probably be closed.

**Comment by kburtram** [comment] 2018-04-05 16:30
I'll close as dup.  @corivera is currently working on this feature and it should be in either April or May release.

**Closed by kburtram** 2018-04-05 16:30 UTC
Labels: edit data, suggestion
