### ISSUE TITLE
Feature request: Query window name change

### ISSUE THREAD

**Issue by bciesielski** [Microsoft/sqlopsstudio#1151] opened 2018-04-13 11:48 UTC
Add the ability to change the name of a query window without saving it to a file.
This would make query window list easier to use instead of guessing what the contents are and going through them all (especially as you can now close and reopen application without losing unsaved query windows). Name changing should be easy to do e.g. selecting an item and pressing F2 and type in place.

If a query is saved to a file the pink (dark theme) DB icon could change to e.g. green

![image](https://user-images.githubusercontent.com/36210825/38733059-d38335ca-3f20-11e8-9436-479245fcfbc3.png)

**Comment by kburtram** [comment] 2018-04-13 16:57
@bciesielski I think this is mostly a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/956.  I'll add a note to that issue to look at this when resolving to verify the full requirements are considered.  Please reactive if you feel the other issue doesn't capture this suggestion.  Thanks!

**Closed by kburtram** 2018-04-13 16:57 UTC

**Comment by bciesielski** [comment] 2018-04-13 17:54
@kburtram yes, indeed we seem to be writing about similiar thing. I gave it +1. Thanks
