### ISSUE TITLE
Keyboard and mouse delimiters not compatible with T-SQL

### ISSUE THREAD

**Issue by JCKodel** [Microsoft/sqlopsstudio#224] opened 2017-11-27 23:13 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---
Delimiters for mouse and keyboard functions are not compatible with T-SQL.

Consider the following query:
```
SELECT 
		@PageUserId = PageUserId,
		@UserId = UserId,
		@Name = Name,
		@Email = Email,
        @Gender = Gender
	FROM OPENJSON(@JSON) WITH
	(
		PageUserId  VARCHAR(32)     '$.tags',
		UserId      VARCHAR(32)     '$.dataInicial',
		Name        VARCHAR(128)    '$.dataFinal',
		Email       VARCHAR(128)    '$.operacoes',
        Gender      VARCHAR(16)		'$.operacoes'
	)
```

If you double-click the @PageUserId, only the PageUserId is selected (not the @). The expected behavior is to consider @PageUserId as a single entity and be selectable with @ when double-clicked.

Also, in the following line:

```
PageUserId  VARCHAR(32)     '$.tags',
```

if you put the keyboard just before the '$.tags' and press Ctrl+Delete, the result will be:

```
PageUserId  VARCHAR(32)     tags',
```

But it should only delete the first ' (single quote).
(I could not reproduce the error, but the first time I've edited this query, I'm pretty sure I pressed Ctrl+Delete after the VARCHAR(32) and the result was VARCHAR(32)tags', (whatever space or tab that existed there was deleted along with the initial '$.

I know, low priority, but would be nice to have the same behavior as Management Studio. =)

**Comment by kevcunnane** [comment] 2017-11-28 00:19
This is somewhat of a duplicate of #143, and the workaround there (change the `editor.wordSeparators` values) applies. I created an API change request in the VSCode repo to track this https://github.com/Microsoft/vscode/issues/39218 as the ideal solution is there.

**Comment by kburtram** [comment] 2018-07-16 16:48
I'll close this as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/143 to reduce the number of related issues we're tracking.  Please add additional comments to that issue if desired.

**Closed by kburtram** 2018-07-16 16:48 UTC
Labels: query editor, suggestion, upstream
