### ISSUE TITLE
Delay to open a store procedure

### ISSUE THREAD

**Issue by gabcastro** [Microsoft/sqlopsstudio#170] opened 2017-11-21 12:45 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.3.9600
---

Steps to Reproduce:

1. Click in a proc with right side of mouse 
2. Select as "Script as Create" 

This operation take a long time to complete, more than when I used SQL Management.
I don't know if is normal but it's a suggestion for fix in next releases.

Regards,

**Comment by GabrielBarriosT** [comment] 2017-11-21 14:49
Had the same issue as well...

**Comment by erickangMSFT** [comment] 2017-11-21 18:27
@gabcastro @GabrielBarriosT  This issue is under investigation currently.

**Comment by llali** [comment] 2017-11-22 22:00
This is a duplicate of #115

**Closed by llali** 2017-11-22 22:00 UTC
Labels: bug, scripting
