### ISSUE TITLE
Allow setting "nicknames" for saved connections

### ISSUE THREAD

**Issue by bradwestness** [Microsoft/sqlopsstudio#1131] opened 2018-04-11 22:17 UTC
It would be nice to be able to set a display name/nickname for saved connections like you can for Registered Servers in SSMS. 

 really useful for remembering which multi-tenant databases are on a particular server, for example.

**Comment by kburtram** [comment] 2018-04-12 21:34
@bradwestness I think this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/1020.  I'll close so we can track in a single issue.  We plan to support this use case, but not sure which release it will come in.

**Closed by kburtram** 2018-04-12 21:34 UTC
