### ISSUE TITLE
Connection Alias

### ISSUE THREAD

**Issue by starmax777** [Microsoft/sqlopsstudio#1772] opened 2018-06-28 10:28 UTC
Issue Type: <b>Feature Request</b>

It would be nice to be able to give a connection an Alias and have it show up in the connections list in place of the server string.  This would allow the user to use names that make sense.
Something like 

Production01, myDatabase (myID)
Production02, myOtherDB (myID)
Test, myDatabase (myID)
Test, myOtherDatabase (myID)

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 6.1.7601

**Comment by starmax777** [comment] 2018-06-28 10:30
Or a DisplayName element...

**Comment by kevcunnane** [comment] 2018-06-28 16:45
I think this is a duplicate of #1020. This is on our backlog - while it is one we'd like to address we don't have it assigned to a release plan for now. I'm going to close this as it's a duplicate, but please do track the other issue so you can see when it progresses.

**Closed by kevcunnane** 2018-06-28 16:45 UTC
Labels: duplicate, suggestion
