### ISSUE TITLE
GO TO Definition missing connection settings

### ISSUE THREAD

**Issue by EricWu91** [Microsoft/sqlopsstudio#791] opened 2018-02-27 12:56 UTC
- SQL Operations Studio Version: 0.26.7 (February Release)

Steps to Reproduce: 
1) Type `EXEC <procName>`
2) Move cursor to `<procName>` 
3) Press F12
A new window with the definition opens.
This window is not connected, and requires a _Connect_  in order to be executed.
![image](https://user-images.githubusercontent.com/9344516/36729792-2103a474-1ba4-11e8-8c53-6cc9a229174a.png)

Is this the intended behavior? Since #6 solves a similar question (i.e. same connection to new window), shouldn't "Keep the previous connection" be expected to happen?

**Comment by kburtram** [comment] 2018-07-19 17:30
Closing as duplicate of https://github.com/Microsoft/sqlopsstudio/issues/825.  Please add any additional info there.  Thanks.

**Closed by kburtram** 2018-07-19 17:30 UTC
Labels: intellisense, query editor, suggestion
