### ISSUE TITLE
Cannot connect to any database using Linux Mint 19

### ISSUE THREAD

**Issue by niklas-e** [Microsoft/sqlopsstudio#1951] opened 2018-07-17 09:08 UTC
Issue Type: <b>Bug</b>

1. Go to "New connection"
2. Type or copy-paste server information and credentials
3. Click "Connect"
4. Loading indicator spins infinitely and doesn't throw any errors. However the software is responsive and I can click "Cancel" to close the connection panel.

I tried to set server info in few ways:
- xxxxxx.database.windows.net
  - Without specified port
  - Set the port 1433 in "Advanced" section
- xxxxxx.database.windows.net,1433
- xxxxxx.database.windows.net:1433

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:50:31.119Z)
OS version: Linux x64 4.15.0-24-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|15.43GB (10.01GB free)|
|Process Argv|/usr/share/sqlops/sqlops --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by aaomidi** [comment] 2018-07-17 22:05
I am unable to repro this on my end. I'll let someone else confirm.

**Comment by niklas-e** [comment] 2018-07-18 06:58
@MattIrv Unfortunately we do not have any on-prem servers. I've tried to restart the Studio and also my laptop, but it didn't help. Just now I tried to reinstall the Studio and it's still occurring.

Here's some additional information related to my case:
- I installed via .deb package
- I haven't been able to connect at all after installing the software, otherwise it seems to work nicely
- I've checked and installed all the mentioned dependencies at https://docs.microsoft.com/en-us/sql/sql-operations-studio/download?view=sql-server-2017

I just noticed the docs stating you are officially only supporting Ubuntu 16.04, but not the latest LTS version. I'm using Linux Mint 19, which is based on Ubuntu 18.04 :(

**Comment by aaomidi** [comment] 2018-07-18 17:53
I tested a fresh install of Ubuntu 18.04 and it worked just fine with a db server on azure.

**Comment by MattIrv** [comment] 2018-07-18 23:00
@niklas-e Thanks for the additional info. This happens on Mint 19 because our logic for determining whether you're using a supported version of Mint hasn't been updated yet for version 19.

I'll make a fix but it probably won't be released for a while since I think it just missed our July release. In the meantime I've attached a patched file that you can download and copy over the corresponding file in your installation (on mine it's at `/usr/share/sqlops/resources/app/extensions/mssql/node_modules/service-downloader/out/platform.js` (rename the attached file from `platform.txt` to `platform.js`) and restart SQL Ops Studio and then it should work.

[platform.txt](https://github.com/Microsoft/sqlopsstudio/files/2207614/platform.txt)

**Comment by witul** [comment] 2018-07-18 23:40
I can confirm what @MattIrv said, but for Gentoo. just added case for gentoo without any version.

**Comment by niklas-e** [comment] 2018-07-19 06:02
@MattIrv cool, it's working now! Thank you!

**Comment by MattIrv** [comment] 2018-07-25 20:59
The [newest insiders build](
https://github.com/Microsoft/sqlopsstudio/releases/tag/0.32.1) contains this fix and it will be included in the August public preview release, so I'll close this issue now. All unsupported Linux distros will now try to use our regular Linux service anyway

**Closed by MattIrv** 2018-07-25 20:59 UTC
Labels: bug, connection
