### ISSUE TITLE
Disable Prompt to Save Unsaved Files

### ISSUE THREAD

**Issue by erichamers** [Microsoft/sqlopsstudio#2276] opened 2018-08-21 18:31 UTC
- SQL Operations Studio Version: 0.31.4

Steps to Reproduce: Close modified query tab without saving it.

Every time I select the top 1000 rows from a table with the right click, it creates a new query as unsaved and when I try to close it as I won't be needing it, it prompts me to save the file. If I'm exploring the tables in a database this can get pretty annoying.

**Comment by kburtram** [comment] 2018-08-22 04:55
@erichamers I think this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/2139.  Please add any comments there, or reactive if this is tracking a different problem.

**Closed by kburtram** 2018-08-22 04:55 UTC
Labels: query editor, suggestion
