### ISSUE TITLE
SqlQuery tooltip

### ISSUE THREAD

**Issue by yunuskiran** [Microsoft/sqlopsstudio#1528] opened 2018-05-31 18:37 UTC
Hi,

Can you change Query window title or add tooltip like smss because when we work with multiple server it can be confuse.

**Comment by abist** [comment] 2018-06-01 17:26
Thanks for the suggestion @yunuskiran. Just to be specific, you want the server name on the tooltip for Query Editor tabs, along with the file name right?

**Comment by yunuskiran** [comment] 2018-06-01 20:56
yes @abist like smss.

**Comment by farkel** [comment] 2018-06-19 13:35
It would be great to have the server listed beside the name or as a tool tip in the Open Editors section of Explorer as well.  I do a lot of adhoc queries so most of my open files are just SQLQuery# so I can't infer context from them.

**Comment by abist** [comment] 2018-06-21 20:52
We're working on this feature. It's a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/1193, so going to close this issue. You can participate in that thread to track this issue.

**Closed by abist** 2018-06-21 20:52 UTC
Labels: query editor, suggestion
