### ISSUE TITLE
Attach mdf file 

### ISSUE THREAD

**Issue by edob95** [Microsoft/sqlopsstudio#1366] opened 2018-05-08 12:57 UTC
- SQL Operations Studio Version:0.29.3 

I have a problem with the attachment of a .mdf file. I don't know ho to do that. 
I tried drag and dropping but I have a message saying that the dimension of the file is too big for the window and I have to use the command --max-memory. Where should I put this command?

I have also tried creating a new database from t-sql but I receive the message that the system can't find the .mdf file. 
Do you have any solution? Because I'm becoming crazy.

Thanks,
Edoardo

**Comment by kburtram** [comment] 2018-05-08 17:08
@edob95 we don't currently have the same support for working with MDF files that SSMS.  There is some discussion of this topic in issue https://github.com/Microsoft/sqlopsstudio/issues/415.  Could you please take a look and see if that discussion address your question?

**Comment by kburtram** [comment] 2018-05-22 17:48
Closing as duplicate of #415

**Closed by kburtram** 2018-05-22 17:48 UTC
Labels: connection, more info, suggestion
