### ISSUE TITLE
Moving between open documents scrolls document to the top

### ISSUE THREAD

**Issue by GabrielBarriosT** [Microsoft/sqlopsstudio#178] opened 2017-11-21 19:12 UTC
- SQL Operations Studio Version:
0.23.6
Steps to Reproduce:
Open two SQL Editors, make sure one has enough text to scroll down, then position the cursor on the bottom of this initial document, then go to the second Document or Tab by either using your mouse or by using ALT+Tab, and then go back to this initial document either using your mouse or by using ALT+Tab, the document will automatically be scrolled to the top and the cursor won't be in the Text Editor anymore...

**Comment by erickangMSFT** [comment] 2017-11-21 20:55
Note: VS Code editor has the expected behavior.

**Comment by GabrielBarriosT** [comment] 2017-11-21 20:57
If this is the expected behavior, can this be removed or change this setting, this is really annoying when editing a document and you need to jump through several editors...

**Comment by HanzoX7** [comment] 2017-11-23 00:18
Not sure if the expected behaviour, but in SSMS 17.3, the cursor location is preserved when switching to different tabs. Real time saver...

**Comment by saurabh500** [comment] 2017-12-06 23:58
@GabrielBarriosT I think what Eric is mentioning is that the tab switching in VSCode behave correctly for the developers to know that this is not an upstream issue :) 

I am closing this as a dupe of https://github.com/Microsoft/sqlopsstudio/issues/114

**Closed by saurabh500** 2017-12-06 23:58 UTC
Labels: bug, query editor
