### ISSUE TITLE
Result export to file - file created without extension.

### ISSUE THREAD

**Issue by ashgadala** [Microsoft/sqlopsstudio#2137] opened 2018-08-03 14:29 UTC
Issue Type: <b>Bug</b>

This is not an big deal in larger scheme of thing that SQL OPS Studio can do. but i want to put this on your radar. 

Up on excuting the query,I use icons next to result grid,when i try to export the data to file. Application fails to add the extension by default. 

for eg: while exporting the data to name.XLSX we have explisiltly indicate the extension XLSX.It would be better if application can do that.  

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kburtram** [comment] 2018-08-03 20:41
@ashgadala I believe this is a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/892.  Please reactive if this is a different issue.

**Closed by kburtram** 2018-08-03 20:41 UTC

**Comment by ashgadala** [comment] 2018-08-05 00:52
I agree
