### ISSUE TITLE
Cannot add count insight

### ISSUE THREAD

**Issue by ManuSQLGeek** [Microsoft/sqlopsstudio#34] opened 2017-11-15 23:28 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. Follow steps at https://docs.microsoft.com/en-gb/sql/sql-operations-studio/tutorial-build-custom-insight-sql-server
2. When adding widget insight data to user-settings throws error Incorrect type : expected "null"

**Comment by EnjoyinMoss** [comment] 2018-01-20 00:10
This is the same as #80

**Comment by kburtram** [comment] 2018-04-25 21:16
Closing as duplicate of #80.  Please reactive if #80 doesn't capture this issue.  Thanks!

**Closed by kburtram** 2018-04-25 21:16 UTC
Labels: bug, insights
