### ISSUE TITLE
Maintain scroll position between tabs

### ISSUE THREAD

**Issue by IAmHopp** [Microsoft/sqlopsstudio#1550] opened 2018-06-05 16:33 UTC
Issue Type: <b>Feature Request</b>

Hi,

I imagine this is a simple request, let me know otherwise, but I'd like for the results pane not to automatically scroll to the top when switching tabs. This'd help a ton when I'm quickly comparing results in different queries that sit accross different tabs, since state is important in that scenario. Always scrolling to the top, as the app does now, breaks my ability to go back and forth and compare rows.

Let me know what you think. Thanks!

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.17134

**Comment by abist** [comment] 2018-06-05 17:37
Closing as it's a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/114

**Closed by abist** 2018-06-05 17:37 UTC
