### ISSUE TITLE
Does not show Table-valued Functions

### ISSUE THREAD

**Issue by 0xAAE** [Microsoft/sqlopsstudio#777] opened 2018-02-24 08:30 UTC
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Connect to SQL-server
2. Expand <Dbname>/Programmability/Table-Valued Functions

You'll see empty tree node while you're sure those functions exist

*SSMS, Visual Studio show table-valued functions successfully
*Other nodes expands well. I tried Azure-hosted server, as LocalDB also

**Comment by emredjan** [comment] 2018-02-26 19:59
Duplicate of #595

**Comment by kburtram** [comment] 2018-04-13 00:39
Closing as duplicate of https://github.com/Microsoft/sqlopsstudio/issues/595 which was closed as fixed.  Please reactive if this is still an issue on current builds.  Thanks!

**Closed by kburtram** 2018-04-13 00:39 UTC
Labels: bug, object explorer
