### ISSUE TITLE
Edit data: cell doesn't revert to original value on hitting Escape key

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/sqlopsstudio#1782] opened 2018-06-28 18:05 UTC
- SQL Operations Studio Version:

Steps to Reproduce:
- Edit the Sales.Orders table in WideWorldImporters
- Change the `PickedByPerson` field in row 1 to `abcd` and tab to next row
- See that an error appears and you're moved back to the original cell
- Hit `Esc` key to exit text entry

Expected:
- Cell reverts to original value
Actual:
- Cell still shows the edited value
- You can change & commit other values - the backend isn't updated
- You only discover the "error" when re-running the query so you refresh the table

![image](https://user-images.githubusercontent.com/10819925/42052218-02846ac8-7ac3-11e8-81a4-08eabfb486b9.png)

**Comment by kburtram** [comment] 2018-06-28 20:32
This looks like a regression in the June Public Preview.

**Comment by alanrenmsft** [comment] 2018-08-16 23:55
the fix has been merged to master branch

**Closed by alanrenmsft** 2018-08-16 23:55 UTC
Labels: bug, edit data, regression
