### ISSUE TITLE
Modifying an existing stored procedure needs an ALTER option

### ISSUE THREAD

**Issue by PLDiCicco** [Microsoft/sqlopsstudio#135] opened 2017-11-18 12:38 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.14393
---

I really like this product so far!!!!

Steps to Reproduce:

1.Open a database -> Programmability -> Stored Procedures -> Right click on an existing procedure
2.The available options are CREATE and DELETE, we need an option for ALTER

**Comment by kevcunnane** [comment] 2017-11-20 21:27
Closing as a duplicate of #118. We can use that one as a tracking issue. Thanks for reporting!

**Closed by kevcunnane** 2017-11-20 21:27 UTC
