### ISSUE TITLE
Application hangs when running procedures with long cursors and multiple print messages

### ISSUE THREAD

**Issue by luismiguelgilbert** [Microsoft/sqlopsstudio#364] opened 2017-12-19 16:36 UTC
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1. execute procedure with long running cursor and multiple printed messages (command PRINT) makes SQLOPS to hang.

This is the procedure:

ALTER PROCEDURE [dbo].[SP_RPT_KARDEX_COMPLETE] AS

IF EXISTS(SELECT NAME FROM sysobjects WHERE name = N'RPT_KARDEX_COMPLETE' AND xtype='U') DROP TABLE RPT_KARDEX_COMPLETE
CREATE TABLE RPT_KARDEX_COMPLETE (
WareHouse_ID_PK INT ,Inventory_ID_PK INT, RowNumber BIGINT
,Creation_Date DATETIME ,Creation_Date_YEAR INT ,Creation_Date_MONTH VARCHAR(100) ,Movimientos VARCHAR(100) ,[TYPE_ID] INT
,Direction VARCHAR(100), Inventory_ID INT, Codigo_Batch_ID BIGINT, Codigo_Move_ID BIGINT, Quantity NUMERIC(18,4), QUANTITY_ NUMERIC(18,4)
,SALDO NUMERIC(18,4), Creation_User VARCHAR(25), Bodega VARCHAR(100), Costo NUMERIC(18,4), Stock_Valorizado NUMERIC(18,4)
)
CREATE NONCLUSTERED INDEX [RPT_KARDEX_COMPLETE_WareHouse_ID_PK] ON [dbo].[RPT_KARDEX_COMPLETE] ([WareHouse_ID_PK] ASC)
CREATE NONCLUSTERED INDEX [RPT_KARDEX_COMPLETE_Inventory_ID_PK] ON [dbo].[RPT_KARDEX_COMPLETE] ([Inventory_ID_PK] ASC)
CREATE NONCLUSTERED INDEX [RPT_KARDEX_COMPLETE_RowNumber] ON [dbo].[RPT_KARDEX_COMPLETE] ([RowNumber] ASC)
CREATE NONCLUSTERED INDEX [RPT_KARDEX_COMPLETE_Creation_Date] ON [dbo].[RPT_KARDEX_COMPLETE] ([Creation_Date] ASC)

									
DECLARE @WarehouseID INT
DECLARE @InventoryID INT
DECLARE @TABLARESULTADO TABLE
(Creation_Date DATETIME ,Creation_Date_YEAR INT ,Creation_Date_MONTH VARCHAR(100) ,Movimientos VARCHAR(200) ,[Type_ID] INT ,Direction VARCHAR(100) ,Inventory_ID INT
,Codigo_Batch_ID BIGINT ,Codigo_Move_ID BIGINT ,Quantity FLOAT ,QUANTITY_ FLOAT ,SALDO FLOAT ,Creation_User VARCHAR(25) ,Bodega VARCHAR(300) ,Costo FLOAT )

BEGIN--ADICIONADO 23-NOV-2017 PARA INCLUIR ITEMS SYNCED DESDE NUEVO A VIEJO (PORQUE NO SE CREA REGISTRO DE ITEM-BODEGA)
	INSERT INTO dbo.WareHouse_Stock ( WareHouse_ID , Inventory_ID , Quantity , Quantity_OnTransit , Quantity_Reserved , Last_User , Last_Date , Company_ID )
	SELECT
	EXISTENTE.Warehouse_Source
	,EXISTENTE.Inventory_ID
	,0 , 0 , 0 , 'MASTER', GETDATE(), 1
	FROM
	(
		SELECT DISTINCT
		Warehouse_Source, Inventory_ID
		FROM dbo.Stock_Move
	)EXISTENTE
	LEFT JOIN
	(
		SELECT DISTINCT
		WareHouse_ID, Inventory_ID 
		FROM dbo.WareHouse_Stock
	)STOCK ON STOCK.Inventory_ID = EXISTENTE.Inventory_ID AND EXISTENTE.Warehouse_Source = STOCK.WareHouse_ID
	WHERE STOCK.Inventory_ID IS NULL

	INSERT INTO dbo.WareHouse_Stock ( WareHouse_ID , Inventory_ID , Quantity , Quantity_OnTransit , Quantity_Reserved , Last_User , Last_Date , Company_ID )
	SELECT
	EXISTENTE.Warehouse_Destination
	,EXISTENTE.Inventory_ID
	,0 , 0 , 0 , 'MASTER', GETDATE(), 1
	FROM
	(
		SELECT DISTINCT
		Warehouse_Destination, Inventory_ID
		FROM dbo.Stock_Move
	)EXISTENTE
	LEFT JOIN
	(
		SELECT DISTINCT
		WareHouse_ID, Inventory_ID 
		FROM dbo.WareHouse_Stock
	)STOCK ON STOCK.Inventory_ID = EXISTENTE.Inventory_ID AND EXISTENTE.Warehouse_Destination = STOCK.WareHouse_ID
	WHERE STOCK.Inventory_ID IS NULL
END

DECLARE COMBINACION_CURSOR CURSOR FOR SELECT DISTINCT WareHouse_ID, Inventory_ID FROM dbo.WareHouse_Stock--SELECT DISTINCT WareHouse_ID, Inventory_ID FROM dbo.WareHouse_Master INNER JOIN dbo.Inv_Master ON 1 = 1
--WHERE WareHouse_ID = 1032
OPEN COMBINACION_CURSOR
FETCH NEXT FROM COMBINACION_CURSOR INTO @WarehouseID, @InventoryID
WHILE @@FETCH_STATUS = 0
BEGIN
	--PRINT 'BODEGA: ' + CONVERT(VARCHAR,@WarehouseID) + ' || Inventario: ' + CONVERT(VARCHAR,@InventoryID)
	--SELECT @WarehouseID AS WarehouseID, @InventoryID AS InventoryID
	DELETE FROM @TABLARESULTADO

	/********************************************************************************************************************************
	STOCK_INICIAL, SOLO SI ES BODEGA 1,2,3
	********************************************************************************************************************************/
	IF @WarehouseID = 1
	BEGIN
			INSERT INTO @TABLARESULTADO
			( Creation_Date ,Creation_Date_YEAR ,Creation_Date_MONTH, Movimientos , [Type_ID] , Direction , Inventory_ID , Codigo_Batch_ID , Codigo_Move_ID , 
			Quantity , QUANTITY_ , SALDO , Creation_User , Bodega , Costo )
			SELECT 
			'2015-01-01', YEAR(CONVERT(DATETIME,'2015-01-01')) AS Creation_Date_YEAR
			,CASE 
								WHEN MONTH(CONVERT(DATETIME,'2015-01-01')) < 10 THEN '0' + CONVERT(VARCHAR,MONTH(CONVERT(DATETIME,'2015-01-01'))) + '-' + DATENAME(m, CONVERT(DATETIME,'2015-01-01'))
								WHEN MONTH(CONVERT(DATETIME,'2015-01-01')) >= 10 THEN CONVERT(VARCHAR,MONTH(CONVERT(DATETIME,'2015-01-01'))) + '-' + DATENAME(m, CONVERT(DATETIME,'2015-01-01'))
			END Creation_Date_MONTH
			,'STOCK INICIAL 2015', 1 ,'Entrada'
			,B.Inventory_ID, 0 AS Codigo_Batch_ID, 0 AS Codigo_Move_ID, bod1 AS Quantity, bod1 AS QUANTITY_
			,0 AS SALDO
			,'LUIS' AS Creation_User
			,'STOCK INICIAL 2015'
			,A.Costo AS COSTO
			FROM dbo.Stock_Inicial A
			--INNER JOIN dbo.Inv_Master B ON A.CODIGO = B.Internal_Code
			INNER JOIN dbo.Inv_Master B ON a.InventoryID = b.Inventory_ID--nuevo
			WHERE B.Inventory_ID = @InventoryID
			--AND bod1 > 0 --nuevo
	END

	IF @WarehouseID = 1007
	BEGIN
			INSERT INTO @TABLARESULTADO
			( Creation_Date ,Creation_Date_YEAR ,Creation_Date_MONTH, Movimientos , [Type_ID] , Direction , Inventory_ID , Codigo_Batch_ID , Codigo_Move_ID , 
			Quantity , QUANTITY_ , SALDO , Creation_User , Bodega , Costo )
			SELECT 
			'2015-01-01', YEAR(CONVERT(DATETIME,'2015-01-01')) AS Creation_Date_YEAR
			,CASE 
								WHEN MONTH(CONVERT(DATETIME,'2015-01-01')) < 10 THEN '0' + CONVERT(VARCHAR,MONTH(CONVERT(DATETIME,'2015-01-01'))) + '-' + DATENAME(m, CONVERT(DATETIME,'2015-01-01'))
								WHEN MONTH(CONVERT(DATETIME,'2015-01-01')) >= 10 THEN CONVERT(VARCHAR,MONTH(CONVERT(DATETIME,'2015-01-01'))) + '-' + DATENAME(m, CONVERT(DATETIME,'2015-01-01'))
			END Creation_Date_MONTH
			,'STOCK INICIAL 2015', 1 ,'Entrada'
			,B.Inventory_ID, 0 AS Codigo_Batch_ID, 0 AS Codigo_Move_ID, bod2 AS Quantity, bod2 AS QUANTITY_
			,0 AS SALDO
			,'LUIS' AS Creation_User
			,'STOCK INICIAL 2015'
			,A.Costo AS COSTO
			FROM dbo.Stock_Inicial A
			--INNER JOIN dbo.Inv_Master B ON A.CODIGO = B.Internal_Code
			INNER JOIN dbo.Inv_Master B ON a.InventoryID = b.Inventory_ID--nuevo
			WHERE B.Inventory_ID = @InventoryID
			--AND bod2 > 0 --nuevo
	END

	IF @WarehouseID = 1008
	BEGIN
			INSERT INTO @TABLARESULTADO
			( Creation_Date ,Creation_Date_YEAR ,Creation_Date_MONTH, Movimientos , [Type_ID] , Direction , Inventory_ID , Codigo_Batch_ID , Codigo_Move_ID , 
			Quantity , QUANTITY_ , SALDO , Creation_User , Bodega , Costo )
			SELECT 
			'2015-01-01', YEAR(CONVERT(DATETIME,'2015-01-01')) AS Creation_Date_YEAR
			,CASE 
								WHEN MONTH(CONVERT(DATETIME,'2015-01-01')) < 10 THEN '0' + CONVERT(VARCHAR,MONTH(CONVERT(DATETIME,'2015-01-01'))) + '-' + DATENAME(m, CONVERT(DATETIME,'2015-01-01'))
								WHEN MONTH(CONVERT(DATETIME,'2015-01-01')) >= 10 THEN CONVERT(VARCHAR,MONTH(CONVERT(DATETIME,'2015-01-01'))) + '-' + DATENAME(m, CONVERT(DATETIME,'2015-01-01'))
			END Creation_Date_MONTH
			,'STOCK INICIAL 2015', 1 ,'Entrada'
			,B.Inventory_ID, 0 AS Codigo_Batch_ID, 0 AS Codigo_Move_ID, bod3 AS Quantity, bod3 AS QUANTITY_
			,0 AS SALDO
			,'LUIS' AS Creation_User
			,'STOCK INICIAL 2015'
			,A.Costo AS COSTO
			FROM dbo.Stock_Inicial A
			--INNER JOIN dbo.Inv_Master B ON A.CODIGO = B.Internal_Code
			INNER JOIN dbo.Inv_Master B ON a.InventoryID = b.Inventory_ID--nuevo
			WHERE B.Inventory_ID = @InventoryID
			--AND bod3 > 0 --nuevo

	END

	/********************************************************************************************************************************
	RECUPERA REGISTROS DE STOCK_PICKING; STOCK_MOVE QUE SON:
	1) PEDIDOS DE OBRA (EGRESOS)
	********************************************************************************************************************************/
	INSERT INTO @TABLARESULTADO
	( Creation_Date ,Creation_Date_YEAR ,Creation_Date_MONTH, Movimientos , [Type_ID] , Direction , Inventory_ID , Codigo_Batch_ID , Codigo_Move_ID , 
	Quantity , QUANTITY_ , SALDO , Creation_User , Bodega , Costo )
	SELECT 
	--A.Creation_Date 
	A.Last_Date AS Creation_Date 
	--,YEAR(A.Creation_Date) AS Creation_Date_YEAR
	,YEAR(A.Last_Date) AS Creation_Date_YEAR
	,CASE 
		--WHEN MONTH(A.Creation_Date) < 10 THEN '0' + CONVERT(VARCHAR,MONTH(A.Creation_Date)) + '-' + DATENAME(m, A.Creation_Date)
		--WHEN MONTH(A.Creation_Date) >= 10 THEN CONVERT(VARCHAR,MONTH(A.Creation_Date)) + '-' + DATENAME(m, A.Creation_Date)
		WHEN MONTH(A.Last_Date) < 10 THEN '0' + CONVERT(VARCHAR,MONTH(A.Last_Date)) + '-' + DATENAME(m, A.Last_Date)
		WHEN MONTH(A.Last_Date) >= 10 THEN CONVERT(VARCHAR,MONTH(A.Last_Date)) + '-' + DATENAME(m, A.Last_Date)
	END Creation_Date_MONTH
	,'PEDIDO DE OBRA' AS Movimientos
	,A.Stock_Picking_Direction_ID
	,'Salida' AS Direction
	,B.Inventory_ID
	,B.Batch_ID AS Codigo_Batch_ID
	,B.Stock_Move_ID AS Codigo_Move_ID
	,B.Quantity
	,(B.Quantity * -1 ) AS QUANTITY_ --como es egreso, entonces se debe restar
	,0 AS SALDO
	,B.Creation_User
	,C.WareHouse_Name AS Bodega
	,B.Unit_Price AS Costo
	FROM dbo.Stock_Picking A
	INNER JOIN dbo.Stock_Move B ON A.Stock_Picking_ID = B.Stock_Picking_ID
	LEFT JOIN dbo.WareHouse_Master C ON A.Warehouse_Destination = C.WareHouse_ID --HAGO JOIN CON DESTINATION PORQUE QUIERO RECUPERAR HACIA DONDE ES EL EGRESO
	WHERE 
	A.Stock_Picking_Direction_ID = 1 --EGRESO
	AND A.Warehouse_Source = @WarehouseID --BODEGA DE DONDE SALE (EN CONJUNTO CON Stock_Picking_Direction_ID = 1)
	AND B.Inventory_ID = @InventoryID --INVENTARIO AL QUE QUEREMOS BUSCAR
	AND A.Estado IN (3,5) --PARA CONSIDERAR UNICAMENTE LOS ESTADOS 3:Completado Y 5:Completado Parcialmente
	AND B.Batch_ID IS NOT NULL
	/********************************************************************************************************************************
	RECUPERA REGISTROS DE STOCK_PICKING; STOCK_MOVE QUE SON:
	2) PEDIDOS DE OBRA (INGRESOS)
	********************************************************************************************************************************/
	INSERT INTO @TABLARESULTADO
	( Creation_Date ,Creation_Date_YEAR ,Creation_Date_MONTH, Movimientos , [Type_ID] , Direction , Inventory_ID , Codigo_Batch_ID , Codigo_Move_ID , 
	Quantity , QUANTITY_ , SALDO , Creation_User , Bodega , Costo )
	SELECT 
	B.Last_Date --tomo el last date porque el ingreso se crea en el mismo momento del ingreso, pero realmente se recibe después de eso, y la fecha correcta es en la que se actualiza el registro
	,YEAR(B.Last_Date) AS Creation_Date_YEAR
	,CASE 
		WHEN MONTH(B.Last_Date) < 10 THEN '0' + CONVERT(VARCHAR,MONTH(B.Last_Date)) + '-' + DATENAME(m, B.Last_Date)
		WHEN MONTH(B.Last_Date) >= 10 THEN CONVERT(VARCHAR,MONTH(B.Last_Date)) + '-' + DATENAME(m, B.Last_Date)
	END Creation_Date_MONTH
	,'PEDIDO DE OBRA' AS Movimientos
	,A.Stock_Picking_Direction_ID
	,'Entrada' AS Direction
	,B.Inventory_ID
	,B.Batch_ID AS Codigo_Batch_ID
	,B.Stock_Move_ID AS Codigo_Move_ID
	,B.Quantity
	,B.Quantity AS QUANTITY_
	,0 AS SALDO
	,B.Creation_User
	,C.WareHouse_Name AS Bodega
	,B.Unit_Price AS Costo
	FROM dbo.Stock_Picking A
	INNER JOIN dbo.Stock_Move B ON A.Stock_Picking_ID = B.Stock_Picking_ID
	LEFT JOIN dbo.WareHouse_Master C ON A.Warehouse_Destination = C.WareHouse_ID --HAGO JOIN CON DESTINATION PORQUE QUIERO RECUPERAR HACIA DONDE ES EL EGRESO
	WHERE 
	A.Stock_Picking_Direction_ID = 2 --INGRESO
	AND A.Warehouse_Source = @WarehouseID --BODEGA DE DONDE SALE (EN CONJUNTO CON Stock_Picking_Direction_ID = 2)
	AND B.Inventory_ID = @InventoryID --INVENTARIO AL QUE QUEREMOS BUSCAR
	AND C.WareHouse_Type_ID <> 4 --QUE EL TIPO DE BODEGA DE DESTINO "NO DEBE SER TIPO PROVEEDOR"
	AND A.Estado IN (3,5) --PARA CONSIDERAR UNICAMENTE LOS ESTADOS 3:Completado Y 5:Completado Parcialmente
	/********************************************************************************************************************************
	RECUPERA REGISTROS DE STOCK_PICKING; STOCK_MOVE QUE SON:
	3) COMPRAS (INGRESOS)
	********************************************************************************************************************************/
	INSERT INTO @TABLARESULTADO
	( Creation_Date ,Creation_Date_YEAR ,Creation_Date_MONTH, Movimientos , [Type_ID] , Direction , Inventory_ID , Codigo_Batch_ID , Codigo_Move_ID , 
	Quantity , QUANTITY_ , SALDO , Creation_User , Bodega , Costo )
	SELECT 
	B.Last_Date --tomo el last date porque el ingreso se crea en el mismo momento del ingreso, pero realmente se recibe después de eso, y la fecha correcta es en la que se actualiza el registro
	,YEAR(B.Last_Date) AS Creation_Date_YEAR
	,CASE 
		WHEN MONTH(B.Last_Date) < 10 THEN '0' + CONVERT(VARCHAR,MONTH(B.Last_Date)) + '-' + DATENAME(m, B.Last_Date)
		WHEN MONTH(B.Last_Date) >= 10 THEN CONVERT(VARCHAR,MONTH(B.Last_Date)) + '-' + DATENAME(m, B.Last_Date)
	END Creation_Date_MONTH
	,'COMPRA' AS Movimientos
	,A.Stock_Picking_Direction_ID
	,'Entrada' AS Direction
	,B.Inventory_ID
	,B.Batch_ID AS Codigo_Batch_ID
	,B.Stock_Move_ID AS Codigo_Move_ID
	,B.Quantity
	,B.Quantity AS QUANTITY_
	,0 AS SALDO
	,B.Creation_User
	--,C.WareHouse_Name AS Bodega
	,E.Partner_Name AS Bodega
	,B.Unit_Price AS Costo
	FROM dbo.Stock_Picking A
	INNER JOIN dbo.Stock_Move B ON A.Stock_Picking_ID = B.Stock_Picking_ID
	LEFT JOIN dbo.WareHouse_Master C ON A.Warehouse_Destination = C.WareHouse_ID --HAGO JOIN CON DESTINATION PORQUE QUIERO RECUPERAR HACIA DONDE ES EL EGRESO
	LEFT JOIN dbo.Partner_Master E ON B.Partner_ID = E.Partner_ID
	WHERE 
	A.Stock_Picking_Direction_ID = 2 --INGRESO
	AND A.Warehouse_Source = @WarehouseID --BODEGA DE DONDE SALE (EN CONJUNTO CON Stock_Picking_Direction_ID = 2)
	AND B.Inventory_ID = @InventoryID --INVENTARIO AL QUE QUEREMOS BUSCAR
	AND C.WareHouse_Type_ID = 4 --QUE EL TIPO DE BODEGA DE DESTINO "NO DEBE SER TIPO PROVEEDOR"
	AND A.Estado NOT IN (4)

	/********************************************************************************************************************************
	RECUPERA REGISTROS DE STOCK_PICKING; STOCK_MOVE QUE SON:
	4) TRANSFERENCIAS INTERNAS (INGRESOS)
	********************************************************************************************************************************/
	INSERT INTO @TABLARESULTADO
	( Creation_Date ,Creation_Date_YEAR ,Creation_Date_MONTH, Movimientos , [Type_ID] , Direction , Inventory_ID , Codigo_Batch_ID , Codigo_Move_ID , 
	Quantity , QUANTITY_ , SALDO , Creation_User , Bodega , Costo )
	SELECT 
	B.Last_Date --tomo el last date porque el ingreso se crea en el mismo momento del ingreso, pero realmente se recibe después de eso, y la fecha correcta es en la que se actualiza el registro
	,YEAR(B.Last_Date) AS Creation_Date_YEAR
	,CASE 
		WHEN MONTH(B.Last_Date) < 10 THEN '0' + CONVERT(VARCHAR,MONTH(B.Last_Date)) + '-' + DATENAME(m, B.Last_Date)
		WHEN MONTH(B.Last_Date) >= 10 THEN CONVERT(VARCHAR,MONTH(B.Last_Date)) + '-' + DATENAME(m, B.Last_Date)
	END Creation_Date_MONTH
	,'TRANSFERENCIA INTERNA' AS Movimientos
	,A.Stock_Picking_Direction_ID
	--,'Entrada' AS Direction
	,CASE 
		WHEN A.Stock_Picking_Direction_ID = 4 AND A.Warehouse_Source = @WarehouseID AND A.Warehouse_Destination = 1 AND b.Last_Date < '2015-03-01' THEN 'Salida'
		ELSE 'Entrada1'
	END Direction
	,B.Inventory_ID
	,B.Batch_ID AS Codigo_Batch_ID
	,B.Stock_Move_ID AS Codigo_Move_ID
	,B.Quantity
	--,B.Quantity AS QUANTITY_
	,CASE 
		WHEN A.Stock_Picking_Direction_ID = 4 AND A.Warehouse_Source = @WarehouseID AND A.Warehouse_Destination = 1 AND b.Last_Date < '2015-03-01' THEN (B.Quantity * -1)
		ELSE B.Quantity
	END QUANTITY_
	,0 AS SALDO
	,B.Creation_User
	,C.WareHouse_Name AS Bodega
	,B.Unit_Price AS Costo
	FROM dbo.Stock_Picking A
	INNER JOIN dbo.Stock_Move B ON A.Stock_Picking_ID = B.Stock_Picking_ID
	LEFT JOIN dbo.WareHouse_Master C ON A.Warehouse_Destination = C.WareHouse_ID --HAGO JOIN CON DESTINATION PORQUE QUIERO RECUPERAR HACIA DONDE ES EL EGRESO
	WHERE 
	A.Stock_Picking_Direction_ID = 4 --INGRESO
	AND A.Warehouse_Source = @WarehouseID --BODEGA DE INGRESO (EN CONJUNTO CON Stock_Picking_Direction_ID = 3)
	AND B.Inventory_ID = @InventoryID --INVENTARIO AL QUE QUEREMOS BUSCAR
	--AND A.Estado IN (2) /*2= COMPLETADO*/
	AND a.Estado NOT IN (4)

	/********************************************************************************************************************************
	RECUPERA REGISTROS DE STOCK_PICKING; STOCK_MOVE QUE SON:
	5) TRANSFERENCIAS INTERNAS (EGRESOS)
	********************************************************************************************************************************/
	INSERT INTO @TABLARESULTADO
	( Creation_Date ,Creation_Date_YEAR ,Creation_Date_MONTH, Movimientos , [Type_ID] , Direction , Inventory_ID , Codigo_Batch_ID , Codigo_Move_ID , 
	Quantity , QUANTITY_ , SALDO , Creation_User , Bodega , Costo )
	SELECT 
	B.Last_Date --tomo el last date porque el ingreso se crea en el mismo momento del ingreso, pero realmente se recibe después de eso, y la fecha correcta es en la que se actualiza el registro
	,YEAR(B.Last_Date) AS Creation_Date_YEAR
	,CASE 
		WHEN MONTH(B.Last_Date) < 10 THEN '0' + CONVERT(VARCHAR,MONTH(B.Last_Date)) + '-' + DATENAME(m, B.Last_Date)
		WHEN MONTH(B.Last_Date) >= 10 THEN CONVERT(VARCHAR,MONTH(B.Last_Date)) + '-' + DATENAME(m, B.Last_Date)
	END Creation_Date_MONTH
	,'TRANSFERENCIA INTERNA' AS Movimientos
	,A.Stock_Picking_Direction_ID
	--,'Salida' AS Direction
	,CASE 
		WHEN A.Stock_Picking_Direction_ID = 3 AND A.Warehouse_Source = @WarehouseID AND A.Warehouse_Source = 1 AND b.Last_Date < '2015-03-01' THEN 'Entrada2'
		ELSE 'Salida'
	END Direction
	,B.Inventory_ID
	,B.Batch_ID AS Codigo_Batch_ID
	,B.Stock_Move_ID AS Codigo_Move_ID
	,B.Quantity
	--,(B.Quantity * -1 ) AS QUANTITY_ --como es egreso, entonces se debe restar
	,CASE 
		WHEN A.Stock_Picking_Direction_ID = 3 AND A.Warehouse_Source = @WarehouseID AND A.Warehouse_Source = 1 AND b.Last_Date < '2015-03-01' THEN (B.Quantity)
		ELSE (B.Quantity * -1 )
	END QUANTITY_
	,0 AS SALDO
	,B.Creation_User
	,C.WareHouse_Name AS Bodega
	,B.Unit_Price AS Costo
	FROM dbo.Stock_Picking A
	INNER JOIN dbo.Stock_Move B ON A.Stock_Picking_ID = B.Stock_Picking_ID
	LEFT JOIN dbo.WareHouse_Master C ON A.Warehouse_Destination = C.WareHouse_ID --HAGO JOIN CON DESTINATION PORQUE QUIERO RECUPERAR HACIA DONDE ES EL EGRESO
	LEFT JOIN dbo.WareHouse_Master D ON B.Warehouse_Destination = D.WareHouse_ID
	WHERE 
	A.Stock_Picking_Direction_ID = 3 --egreso
	AND A.Warehouse_Source = @WarehouseID --BODEGA DE EGRESO (EN CONJUNTO CON Stock_Picking_Direction_ID = 3)
	AND B.Inventory_ID = @InventoryID --INVENTARIO AL QUE QUEREMOS BUSCAR
	--AND A.Estado IN (2) /*2= COMPLETADO*/

	/********************************************************************************************************************************
	RECUPERA REGISTROS DE STOCK_PICKING; STOCK_MOVE QUE SON:
	6) AJUSTE DE INVENTARIO (INGRESOS / EGRESOS)
	********************************************************************************************************************************/
	INSERT INTO @TABLARESULTADO
	( Creation_Date ,Creation_Date_YEAR ,Creation_Date_MONTH, Movimientos , [Type_ID] , Direction , Inventory_ID , Codigo_Batch_ID , Codigo_Move_ID , 
	Quantity , QUANTITY_ , SALDO , Creation_User , Bodega , Costo )
	SELECT 
	A.Creation_Date
	,YEAR(A.Creation_Date) AS Creation_Date_YEAR
	,CASE 
		WHEN MONTH(A.Creation_Date) < 10 THEN '0' + CONVERT(VARCHAR,MONTH(A.Creation_Date)) + '-' + DATENAME(m, A.Creation_Date)
		WHEN MONTH(A.Creation_Date) >= 10 THEN CONVERT(VARCHAR,MONTH(A.Creation_Date)) + '-' + DATENAME(m, A.Creation_Date)
	END Creation_Date_MONTH
	,'AJUSTE DE INVENTARIO' AS Movimientos
	,0 AS Stock_Picking_Direction_ID
	--,'Salida' AS Direction
	,CASE
		WHEN C.Warehouse_Source = 2 AND C.Warehouse_Destination = @WarehouseID THEN 'Entrada'
		WHEN C.Warehouse_Source = @WarehouseID AND C.Warehouse_Destination = 2 THEN 'Salida'
	END Direction
	,C.Inventory_ID
	,C.Batch_ID AS Codigo_Batch_ID
	,C.Stock_Move_ID AS Codigo_Move_ID
	,C.Quantity
	,CASE
		WHEN C.Warehouse_Source = 2 AND C.Warehouse_Destination = @WarehouseID THEN (C.Quantity )  --como es INgreso, entonces se debe SUMAR
		WHEN C.Warehouse_Source = @WarehouseID AND C.Warehouse_Destination = 2 THEN (C.Quantity * -1 )  --como es egreso, entonces se debe RESTAR
	END QUANTITY_ 
	,0 AS SALDO
	,C.Creation_User
	,D.WareHouse_Name AS Bodega
	,C.Unit_Price AS Costo
	FROM dbo.Stock_Inventory A
	INNER JOIN dbo.Stock_Inventory_Rel B ON B.Stock_Inventory_ID = A.Stock_Inventory_ID
	INNER JOIN dbo.Stock_Move C ON B.Stock_Move_ID = C.Stock_Move_ID
	INNER JOIN dbo.WareHouse_Master D ON D.WareHouse_ID = @WarehouseID
	WHERE A.Warehouse_ID = @WarehouseID --NO IMPORTA SI AUMENTA O DISMINUYE EL STOCK, IGUAL ESTA COLUMNA ES LA BODEGA AFECTADA
	AND C.Inventory_ID = @InventoryID

	/********************************************************************************************************************************
	QUERY QUE DEVUELVE RESULTADO
	********************************************************************************************************************************/
	IF(@WarehouseID IN (1,1007, 1008))
	BEGIN
		DELETE FROM @TABLARESULTADO WHERE Creation_Date < '2015-01-01'
	END
	--SELECT * FROM @TABLARESULTADO WHERE Inventory_ID = @InventoryID  ORDER BY 1
	--SELECT *,ROW_NUMBER() OVER ( ORDER BY CONVERT(DATE,Creation_Date), [TYPE_ID] DESC) AS 'RowNumber' FROM @TABLARESULTADO ORDER BY 1
	INSERT INTO RPT_KARDEX_COMPLETE
	SELECT @WarehouseID, @InventoryID, ROW_NUMBER() OVER ( ORDER BY TABLA1.Creation_Date),
	TABLA1.Creation_Date ,TABLA1.Creation_Date_YEAR ,TABLA1.Creation_Date_MONTH ,TABLA1.Movimientos ,TABLA1.[Type_ID] ,TABLA1.Direction ,TABLA1.Inventory_ID ,TABLA1.Codigo_Batch_ID
	,TABLA1.Codigo_Move_ID ,TABLA1.Quantity ,TABLA1.QUANTITY_ 
	,/*TABLA1.SALDO*/SUM(TABLA2.QUANTITY_) AS SALDO
	,TABLA1.Creation_User 
	,TABLA1.Bodega 
	,TABLA1.Costo
	,SUM(TABLA2.QUANTITY_) * TABLA1.Costo AS Stock_Valorizado
	FROM 
	(SELECT *,ROW_NUMBER() OVER ( ORDER BY Creation_Date) AS 'RowNumber' FROM @TABLARESULTADO)TABLA1
	INNER JOIN
	(SELECT *,ROW_NUMBER() OVER ( ORDER BY Creation_Date) AS 'RowNumber' FROM @TABLARESULTADO)TABLA2
	ON TABLA1.RowNumber >= TABLA2.RowNumber
	GROUP BY 
	TABLA1.Creation_Date ,TABLA1.Creation_Date_YEAR ,TABLA1.Creation_Date_MONTH, TABLA1.Movimientos ,TABLA1.[Type_ID] ,TABLA1.Direction ,TABLA1.Inventory_ID ,TABLA1.Codigo_Batch_ID
	,TABLA1.Codigo_Move_ID ,TABLA1.Quantity ,TABLA1.QUANTITY_ ,TABLA1.SALDO ,TABLA1.Creation_User ,TABLA1.Bodega ,TABLA1.Costo
	--ORDER BY TABLA1.Creation_Date, TABLA1.Direction DESC
	--PRINT 'BODEGA: ' + CONVERT(VARCHAR,@WarehouseID) + ' || Inventario: ' + CONVERT(VARCHAR,@InventoryID)
	--SELECT @WarehouseID AS WarehouseID, @InventoryID AS InventoryID
FETCH NEXT FROM COMBINACION_CURSOR INTO @WarehouseID, @InventoryID
END
CLOSE COMBINACION_CURSOR
DEALLOCATE COMBINACION_CURSOR

**Comment by kburtram** [comment] 2018-07-19 15:12
This may be related to https://github.com/Microsoft/sqlopsstudio/issues/304.

**Comment by kburtram** [comment] 2018-08-22 03:42
Closing as a duplicate of https://github.com/Microsoft/sqlopsstudio/issues/268 which is being actively worked on for the September release.

**Closed by kburtram** 2018-08-22 03:42 UTC
Labels: bug, query execution
