### ISSUE TITLE
NULL vs "NULL" missing color diff

### ISSUE THREAD

**Issue by davidkallesen** [Microsoft/sqlopsstudio#781] opened 2018-02-26 08:47 UTC
- SQL Operations Studio Version: 0.26.7

If an idiot has created a row with the text "NULL" instead of NULL - it not possible to see the difference in the results-view in any color-theme.

**Comment by kburtram** [comment] 2018-04-13 00:57
Closing as duplicate of https://github.com/Microsoft/sqlopsstudio/issues/217

**Closed by kburtram** 2018-04-13 00:57 UTC
Labels: bug, query editor
